syntax = "proto3";
package dataStorageType.v0;

option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/dataStorageType/v0";

// This API is to be used by :
// This defines the enum for the data storage type
// enhance this in the future to include more data storage types

// This defines the enum for the RDBMS data storage type
// Extend this in the future to include more RDBMS types
enum RDBMSType {
  RdbmsUnknown = 0;
  CockroachDB = 1;
  PostgresqlDB = 2;

}
// This defines the enum for the NoSQL data storage type
// Extend this in the future to include more NoSQL types
enum NoRDBMSType {
  NoRdbmsUnknown = 0;
  BadgerDB = 1;
  MongoDB = 2;
  RedisDB = 3;
  InfluxDB = 4;
}
// This defines the enum for the deployment type
enum DeploymentType {
  DeploymentTypeUnknown = 0;
  OnPrem = 1;
  Cloud = 2;
}
// This defines the message for the data storage type
// it must include at least one DB type and the deployment type
message DataStorageTypes {
optional RDBMSType rdbmsType = 1;
optional NoRDBMSType noRdbmsType = 2;
DeploymentType deploymentType = 3;
}