syntax = "proto3";

package deviceData;
option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/deviceData/v1";

// DeviceData defines generic message structures exchanged between the Agent and the Backend related to the device data

message DataTimestamp {
  int64 timestamp = 1; // device's UTC timestamp UNIX nanoseconds
}
message BeaconStructure {
  string uuid = 1;
  int32 major = 2;
  int32 minor = 3;
  int32 rssi = 4;
}

message GpsCoords {
  string latitude = 1;
  string longitude = 2;
}

message MaWaRouteDataStruct {
  DataTimestamp timestamp = 1;
  optional BeaconStructure beacon = 2;
  optional GpsCoords gpsCoords = 3;
  DataPacketMetadata metadata = 4;
}

message DeviceData {
  DataTimestamp timestamp = 1;
  string data = 2; // contains device data formatted in json
  DataPacketMetadata metadata = 3;
}
message DataPacketMetadata {
  string signature = 1;
  bool isRowVerifiable = 2;
}

message GetAgentDataReq {
  string agentID = 1; // use this for the agent or the identity ID; todo: rename this field to device ID
  QueryStruct query = 2; // this is to create the query structure
  bool isAgent = 3; // true if data is requested for an agent, false if data is requested for an identity
}

message GetAgentDataRes {
  DeviceData data = 1; // json data stored in the database
  string deviceDataColumnNames = 2; // json formatted column names
}

message GetAgentDataStatReq {
  string agentID = 1;
  bool isAgent = 2;
  QueryStruct query = 3; // this is to create the query structure
}

message GetAgentDataStatRes {
  int64 dataCount = 1;
  int64 totalVerifiableData = 2;
  int64 totalUnverifiableData = 3;
  repeated int64 listOfUnverifiableData = 4; // todo: send list of rowid in the future
  int64 statsLastUpdatedOn = 5;
}
// used for querying data from the backend for a specific time range
message QueryStruct{
  int64 startTimestamp = 2;
  int64 endTimestamp = 3;
}