syntax = "proto3";

package deviceContext;
option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/deviceContext/v1";

// Contains generic messages and their different versions that are used across multiple services and endpoints


// Device context from the device in relation to the device identity
message DeviceContext {
  repeated MacAddress macAddresses = 1; //optional, all MAC addresses available to be picked up by the agent
  string ipAddress = 2; // optional, IP address
  string cpu = 3; // optional, number of CPUs available
  string ram = 4; // optional, RAM size on the device
  string imeiNumber = 5; // optional, International Mobile Equipment Identity, optional, capture if one is available
  OsInfo osType = 6;
}
// OsInfo message structure defining standard OS info used within the system
message OsInfo {
  string osType = 1; // optional, e.g. darwin, windows, etc.
  string arch = 2; // optional, e.g. amd64 etc.
}
// list of macAddresses from the devices
message MacAddress {
  int32 mtu = 1; // optional, maximum transmission unit
  string macAddress = 2; // optional
  string name = 3; // interface's name e.g. en0
}