syntax = "proto3";
package did;
option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/did/v1";

enum Type {
    Unknown = 0;
    EcdsaSecp256k1VerificationKey2019 = 1;
    EcdsaSecp256k1VerificationKey2018 = 2;
}

enum Method {
    scurid = 0;
}
message PublicKey {
  string id = 1;
  Type type = 2; //Encryption mechanism such as EcdsaSecp256k1VerificationKey2019
  string controller = 3; //Controlling authority of the DID
  string address = 4;
}

message Service {
  string id = 1;
  string serviceEndpoint = 2; // service URL
}

message Document {
  string id = 1; //DID Identifier
  repeated string context = 2;
  repeated PublicKey authentication = 3;
  repeated Service   service = 4;
  repeated PublicKey publickey = 5;
  repeated PublicKey revoked = 6;
  uint64 created = 7;
  uint64 updated = 8;
  string controller = 9; //Controlling authority of the DID
  Type type = 10; //Encryption mechanism such as EcdsaSecp256k1VerificationKey2019
}

message DID {
  string method = 1;
  string identifier = 2;
  string fragment = 3;
  string path = 4;
}

// DIDStatus is the status of the DID
enum DIDStatus {
  Inactive = 0;
  Approved = 1;
  Pending = 2;
  Revoked = 3;
  Rejected = 4;
}

