syntax = "proto3";
import "certificate.proto";
package integration;
option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/integration/v0";

// This defines the message structures for different platforms and their required configuration details
// This information will be stored within Scurid Server

// For Thingworx Server
message ThingWorx {
  string thingWorxURL = 1; // thingworx server and port information e.g. https://localhost:443/Thingworx
  string appKey = 2; // thingworx app key created for Scurid server to authenticate with
  bool useThingWorxEntityNameToDownloadAppKey = 3; // if true, then the app key will be downloaded from thingworx using the entity name
}

// For Hawkbit Server
message Hawkbit {
  string hawkbitURL = 1 ; // hawkbit server URL & port information e.g. https://localhost:8080
  string username = 2; // username from Hawkbit server
  string password = 3; // password from Hawkbit server
}

// For Azure IoT & Azure Device Provisioning Service
message Azure {
  bytes csrSigningCertificate = 1; // this is the certificate used to sign the CSR to issue device certificates
  bytes privateKey = 2; // this is the private key used to sign the CSR to issue device certificates
}

// IntegrationDetails contains information on integration with 3rd party platforms
message IntegrationDetails  {
  string hawkbitTargetSecretKey = 1; // a target in Hawkbit is device, when a device is pre-provisioned it will create a secret key which is specific to each device
  string deviceCertificateSigningRequest = 2; // this is the certificate signing request received from the agent.
  bytes deviceCertificate = 3;              // if Azure is enabled, and agent is approved, scurid server will sign the request to generate the certificate, which we can store here
  IntegrationStatus               integrationStatus = 4;
  string thingworxApplicationKey = 5; // this is the device application key issued from ThingWorx
  string thingworxAppKeyName = 6; // this is the name of the app key in ThingWorx
  certificate.v1.CSRCustom csrCustom = 7; // this is the custom CSR information
}

// IntegrationStatus should be used to track which 3rd party integrations are enabled.
message IntegrationStatus {
  bool thingWorxEnabled = 1; // is thingworx integration enabled
  bool hawkbitEnabled = 2; // is hawkbit integration enabled
  bool azureEnabled = 3; // is azure integration enabled
}