syntax = "proto3";
import "google/protobuf/descriptor.proto";
package metadata.v0;
option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/metadata/v0";

// Define a custom option for specifying operation type
enum OperationType {
  UNKNOWN = 0; // default value
  READ = 1; // like GET
  WRITE = 2; // like CREATE
  UPDATE = 3; // like MODIFY
  DELETE = 4; // like REMOVE
}

// Extend the google.protobuf.MethodOptions to include our custom option
extend google.protobuf.MethodOptions {
  // This defines a custom option named "operation_type"
  // It's not recommended to use low numbers for custom options
  // because those are typically reserved for regular field numbers.
  // To avoid potential conflicts and adhere to best practices, it's advisable to choose a number
  // in the extension range (e.g., 50001 or another number within the valid range
  // that you know is not being used for something else in your application).
  // so we choose 50001
  repeated OperationType operationType = 50001;
}