syntax = "proto3";
import "google/api/annotations.proto";
import "metadata/metadata.proto";
import "deviceContext.proto";
import "platformapiv2.proto";
import "platformInternal.proto";
package scuridplatformagentapi.v1;

option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/scuridplatformagentapi/v1";

// This API is to be used by :
// * Scurid Edge Agent when attempting to communicate with Scurid SSI Service, as edge agents will usually not connect to the SSI Service, therefore ScuridPlatformAgentAPI works as a central administration hub for customers to manage their devices
// * Desktop apps


service ScuridPlatformAgentAPI {

  // Track requests from new devices to register them on the SSI Service
  rpc GetPendingRequestsList (GetPendingRequestsListReq) returns (stream GetPendingRequestsListRes) {
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/getpendingrequestslist"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Verify signature of the payload
  // Currently only string payloads are supported
  rpc VerifySignature (VerifySignatureReq) returns (VerifySignatureRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/verifysignature"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Primarily to be used for DID Generation of the platform to be used for registering platform application for that customer
  // This should make an internal call to the Scurid SSI Service and store the DID value in local storage in encrypted wallet
  rpc CreateIdentity (CreateIdentityReq) returns (CreateIdentityRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/createidentity"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
  };

  // Sign a given payload with platform's DID
  rpc SignPayload (SignPayloadReq) returns (SignPayloadRes) {
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/signpayload/payloads/{payload}/dids/{did}"
    };
    option (metadata.v0.operationType) = READ;
  };

  // As platform agent must track every incoming request for DID registration in local DB storage, this service returns the list of all the DIDs that were rejected by the customer to be registered with Scurid SSI Service. This is mainly a bookkeeping service
  rpc GetRejectedIdentitiesList (GetRejectedIdentitiesListReq) returns (stream GetRejectedIdentitiesListRes) {
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/getrejectedidentitieslist"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Fetches the list of all the DIDs that were successfully registered in Scurid SSI Service, this list must be kept internally fresh by the platform's internal service
  rpc GetValidIdentitiesList (GetValidIdentitiesListReq) returns (stream GetValidIdentitiesListRes) {
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/getvalididentitieslist"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Fetches details available on a given identity in local DB storage, data on this identity must be kept fresh by internal services
  rpc GetValidIdentityInfo (GetValidIdentityInfoReq) returns (GetValidIdentityInfoRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/getvalididentityinfo"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Identities returned by GetPendingRequestsList if they are rejected by the customer from the flutter app, they of course MUST not be registered with Scurid SSI Service, but at the same time should be recorded in the local DB
  rpc RecordRejectedDID (RecordRejectedDIDReq) returns (RecordRejectedDIDRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/recordrejecteddid"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
  };
  // this endpoint is for devices to call Platform Agent to register them
  // Normally will be used by devices wanting to registering for the first time, or if a new DID has been generated on an existing device
  rpc RequestRegistrationOfDevice (RequestRegistrationOfDeviceReq) returns (RequestRegistrationOfDeviceRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/requestregistrationofdevice"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
  };

  // This endpoint is primarily meant for devices to get validation from Platform Application
  // if their DID was registered on the blockchain
  rpc RequestIdentityStatus (RequestIdentityStatusReq) returns (RequestIdentityStatusRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/requestidentitystatus"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };

  // To be called from desktop app for getting the path where DB should be initialized
  rpc LocalStorageInit (LocalStorageInitReq) returns (LocalStorageInitRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/localstorageinit"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
  };

  // A call to local storage to get list of all available device DIDs
  rpc GetAllDevicesList (GetAllDevicesListReq) returns (GetAllDevicesListRes) {
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/getalldeviceslist"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Wraps the call for SSI Service API with same name VerifyDeviceDID
  rpc VerifyDeviceDID (VerifyDeviceDIDReq) returns (VerifyDeviceDIDRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/verifydevicedid"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Wraps the call for SSI Service API with same name RevokeDeviceDID
  rpc RevokeDeviceDID (RevokeDeviceDIDReq) returns (RevokeDeviceDIDRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/revokedevicedid"
      body: "*"
    };
    option (metadata.v0.operationType) = UPDATE;
  };

  // Wraps the call for SSI Service API with same name RegisterDeviceDID
  rpc RegisterDeviceDID (RegisterDeviceDIDReq) returns (RegisterDeviceDIDRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/registerdevicedid"
      body: "*"
    };
    option (metadata.v0.operationType) = UPDATE;
  };

  // To provide Platform DID from the local gRPC platform storage
  rpc GetPlatformDID (GetPlatformDIDReq) returns (GetPlatformDIDRes) {
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/getplatformdid"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Provides device's data with signature for each payload
  // returned rows have boolean confirmation attached to each row
  // True denotes that the device's payload has valid signature, false denotes otherwise
  rpc GetDevicePayloadsWithSignature (GetDevicePayloadsWithSignatureReq) returns (GetDevicePayloadsWithSignatureRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/getdevicepayloadswithsignature"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };

  // PostDeviceDataWithSignature to be called from edge devices to post / send their device data with signature to Platform
  rpc PostDeviceDataWithSignature (PostDeviceDataWithSignatureReq) returns (PostDeviceDataWithSignatureRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/postdevicedatawithsignature"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
    option (metadata.v0.operationType) = UPDATE;
  }
  // Provides list of countries
  rpc GetCountriesList(GetCountriesListReq) returns (GetCountriesListRes){
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/getcountrieslist"
    };
    option (metadata.v0.operationType) = READ;
  }

  rpc GetLicenseStatus(GetLicenseStatusReq) returns (GetLicenseStatusRes){
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/getlicensestatus"
    };
    option (metadata.v0.operationType) = READ;
  }

  // Signs a byte array payload with identity
  rpc SignBytePayloadWithIdentity (SignBytePayloadWithIdentityReq) returns (SignBytePayloadWithIdentityRes){
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/signbytepayloadwithidentity"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Verifies a byte array payload with identity
  rpc VerifyBytePayloadWithIdentity (VerifyBytePayloadWithIdentityReq) returns (VerifyBytePayloadWithIdentityRes){
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/verifybytepayloadwithidentity"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };
  // Adds tags for categorization of the identities
  rpc AddTags(AddTagsReq) returns (AddTagsRes){
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/addtags"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
  };

  // Removes existing tags from the identity
  rpc RemoveTags(RemoveTagsReq) returns (RemoveTagsRes){
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/removetags"
      body: "*"
    };
    option (metadata.v0.operationType) = DELETE;
  };

  // Get existing tags
  rpc GetTags(GetTagsReq)returns(stream GetTagsRes){
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/gettags"
    };
    option (metadata.v0.operationType) = READ;
  };

  // AssignTagsToIdentity assign one more tags to an identity
  rpc AssignTagsToIdentity(AssignTagsToIdentityReq) returns(AssignTagsToIdentityRes){
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/assigntagstoidentity"
      body: "*"
    };
    option (metadata.v0.operationType) = UPDATE;
  };

  // Lists all the identities assigned to a Tag
  rpc ListIdentitiesUnderATag(ListIdentitiesUnderATagReq) returns (stream ListIdentitiesUnderATagRes){
    option (google.api.http) = {
      get: "/v1/scuridplatformagentapi/listidentitiesunderatag"
    };
    option (metadata.v0.operationType) = READ;
  };

  // Used for uploading files to the server
  rpc UploadFiles(stream UploadFilesReq) returns (UploadFilesRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/uploadfiles"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
  };

  // Used for downloading device pkgs
  rpc DownloadFiles(DownloadFilesReq) returns (stream DownloadFilesRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/downloadfiles"
      body: "*"
    };
    option (metadata.v0.operationType) = READ;
  };

  // FileStorePath provides path for the device files
  rpc FileStorePath(FileStorePathReq) returns (FileStorePathRes) {
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/filestorepath"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
    option (metadata.v0.operationType) = UPDATE;
  };

  // RecordAppLogs records Scurid App logs
  rpc RecordAppLogs (platform.v2.RecordAppLogsReq) returns (platform.v2.RecordAppLogsRes){
    option (google.api.http) = {
      post: "/v1/scuridplatformagentapi/recordapplogs"
      body: "*"
    };
    option (metadata.v0.operationType) = WRITE;
  };
}

//
// General section
//

message EmptyRequest {
}

//
// ScuridPlatformAgentAPI section
//
message GetLicenseStatusReq{
  // left blank intentionally
}

message GetLicenseStatusRes {
  bool licStatus = 1; // false if status not active; true otherwise
  string licType = 2; // type of the license small, developer etc.
  int64 validFrom = 3; // valid from timestamp
  int64 validUntil = 4; // valid until timestamp
}

message GetCountriesListReq {
  // left blank intentionally
}

message GetCountriesListRes {
  repeated CountriesStruct data = 1;
}

message CountriesStruct {
  string name = 1;
}


message PostDeviceDataWithSignatureReq {
  repeated PostDeviceDataWithSignatureStruct dataSet = 1;
}

message PostDeviceDataWithSignatureRes {
  bool status = 1;
}

message PostDeviceDataWithSignatureStruct {
  string deviceDID = 1;
  string deviceName = 2;
  int32 dataTimestamp = 3;
  string payload = 4;
  string signature = 5;
}

message GetPendingRequestsListReq {
  // empty request
}

message GetDevicePayloadsWithSignatureReq {
  string deviceDid = 1;
  string deviceName = 2; // if deviceName is used all payloads are returned from that device, it may have used multiple DIDs
}

message GetDevicePayloadsWithSignatureRes {
  repeated GetDevicePayloadsWithSignatureStruct rows = 1;
}

message GetDevicePayloadsWithSignatureStruct {
  string deviceDID = 1;
  string deviceName = 2;
  int32 dataTimestamp = 3;
  string payload = 4;
  string signature = 5;
  bool isValid = 6;

}

message GetPendingRequestsListRes {
  PendingRequestsStruct rows = 1;
}

message PendingRequestsStruct {
  string did = 1;
  int64 requestTimestamp = 2;
  string versionInfo = 3;
  int64 created_on = 4;
  string device_name = 5;
  bool isLocal = 6;
  deviceContext.DeviceContext deviceContext = 7; // helps to onboard and bind a device to an identity
  AgentInfoForDID agentInfoForDID = 8; // if there is an agent to which this identity belongs
}

message VerifySignatureReq {
  string signature = 1;
  string payload = 2;
  string did = 3;
}

message VerifySignatureRes {
  bool isValid = 1;
}

message CreateIdentityReq {
  NewPlatformUserInfo customerInfo = 1;
}

message CreateIdentityRes {
  string did = 1;
}

message SignPayloadReq {
  string payload = 1;
  string did = 2;
}

message SignPayloadRes {
  string signature = 1;
}

message GetRejectedIdentitiesListReq {
  // empty request
}

message GetRejectedIdentitiesListRes {
   RejectedIdentitiesListStruct rows = 1;
}

message RejectedIdentitiesListStruct {
  string did = 1;
  string vInfo = 2; // edge agent version used for creating DID
  int64 rejectionTimestamp = 3;
  int64 revokedOn = 4;
  int64 created_on = 5;
  string device_name = 6;
  bool isLocal = 7; // if checked identities are not registered on DLT but only local database
  deviceContext.DeviceContext deviceContext = 8; // helps to onboard and bind a device to an identity
  AgentInfoForDID agentInfoForDID = 9; // if there is an agent to which this identity belongs
}

message GetValidIdentitiesListReq {
  // empty request
}

message GetValidIdentitiesListRes {
  ValidIdentitiesListStruct rows = 1;
}

message ValidIdentitiesListStruct {
  string did = 1;
  string vInfo = 2; // edge agent version used for creating DID
  int64 created_on = 3;
  int64 last_verified_on = 4;
  string device_name = 5;
  bool isLocal = 6; // if checked identities are not registered on DLT but only local database
  string path = 7; // device pkg file store on the client side
  deviceContext.DeviceContext deviceContext = 8; // helps to onboard and bind a device to an identity
  AgentInfoForDID agentInfoForDID = 9; // if there is an agent to which this identity belongs
}

message GetValidIdentityInfoReq {
  string did = 1;
}

message GetValidIdentityInfoRes {
  string vInfo = 1; // edge agent version used for creating DID
  int64 lastVerifiedOn = 2;
  int64 created_on = 3;
  string device_name = 4;
  bool isLocal = 5; // if checked identities are not registered on DLT but only local database
  string path = 6; // device pkg file store on the client side
  deviceContext.DeviceContext deviceContext = 7; // helps to onboard and bind a device to an identity
  AgentInfoForDID agentInfoForDID = 9; // if there is an agent to which this identity belongs
}


message RecordRejectedDIDReq {
  string did = 1;
  int64 rejectedOn = 2; // timestamp of rejection // UTC
  bool isLocal = 3; // defaults to false, if the identity was approved previously use that state
}

message RecordRejectedDIDRes {
  bool status = 1;
}

message RequestRegistrationOfDeviceReq {
  string deviceDID = 1;
  int64 requestedOn = 2; // UTC timestamp of request from device, this value MUST come from device
  string vInfo = 3; // edge agent version used for generating DID
  string device_name = 4; // name with which customer, user identifies it uniquely, this could also be a name in the IIoT Platform
  deviceContext.DeviceContext deviceContext = 5; // helps to onboard and bind a device to an identity
  bytes signatureOnDeviceContext = 6; // hash calculated on the fields requestedOn + deviceDID. THIS must be sent by the agent and will be recorded on the backend and used for future verification.
  AgentInfoForDID agentInfoForDID = 7; // if there is an agent to which this identity belongs
}
message AgentInfoForDID {
  string agentDID = 1; // if device DID to be bound to an agent
  string statusKey = 2; // to be delivered from the backend
}

// this only provides a confirmation if request has been successfully received.
// Whether it's approved or rejected, will be handled by respective service
// This info will be added to the Platform Agent's local storage
message RequestRegistrationOfDeviceRes {
  bool status = 1; // only returns confirmation that the request has been received
}

message RequestIdentityStatusReq {
  string deviceDID = 1;
}

// response is one of the following
message RequestIdentityStatusRes {
  string status = 1;
}

message LocalStorageInitReq {
  string storagePath = 1;
}

message LocalStorageInitRes {
  bool status = 1; // try to return actual error from the OS if any, a success message
}


message GetAllDevicesListReq {
  // empty request
}

message GetAllDevicesListRes {
  repeated AllDevicesListStruct rows = 1;
}

message AllDevicesListStruct {
  string did = 1;
  string deviceName = 2; // human readable name of the device
  string statusOfDID = 3;
  string versionInfo = 4;
  int64 createdOn = 5;
}

message VerifyDeviceDIDReq {
  string platform_did = 1;
  string device_did = 2;

}

message VerifyDeviceDIDRes {
  bool status = 1;
}

message RevokeDeviceDIDReq {
  string device_did = 1;
  string platform_did = 2;
}

message RevokeDeviceDIDRes {
  bool status = 1;
}

message RegisterDeviceDIDReq {
  string deviceDid = 1;
  string platformDid = 2; // platform did
  bool isLocal = 3; // if checked identites are not registered on DLT but only local database
}

message RegisterDeviceDIDRes {
  bool status = 1;
}

message GetPlatformDIDReq {
  // empty request
}

message GetPlatformDIDRes {
  string platform_did = 1;
  string status = 2;
}

message SignBytePayloadWithIdentityReq{
  bytes payload = 1; // array if bytes  to be signed
  string did = 2; // identity i.e. did:scurid:XXXXXXXXXXX ; NOTE identity is case sensitive
}

message SignBytePayloadWithIdentityRes{
  string signature = 1; // generated signature
}

message VerifyBytePayloadWithIdentityReq{
  string signature = 1;
  bytes payload = 2;
  string did = 3; //identity i.e. did:scurid:XXXXXXXXXXX ; NOTE: identity is case sensitive
}

message VerifyBytePayloadWithIdentityRes{
  bool isValid = 1; // true if valid, else false (Defaults to False)
}


//
// Platform Registration Message
//

// struct to be attached to the Platform's DID registration
message NewPlatformUserInfo {
  string firstName = 1;
  string lastName = 2;
  string email = 3;
  string country = 4;
  bool isEnterpriseUser = 5;
  string enterpriseFullName = 6;
  string did = 7;
  string emailRegistrationCode = 8; // this is the code sent to the user's email for verification
}


message TagStruct{
  string tagName = 1;
}

message AddTagsReq {
  repeated TagStruct tags = 1; // one or more tags to be created in the system
}
message AddTagsRes {
  bool result = 1; // boolean result, True if all gets created else false
}


message RemoveTagsReq {
  repeated TagStruct tags = 1; // tags to be deleted from the system
  string did = 2; // this generally the device identity
}
message RemoveTagsRes{
  bool result = 1; // boolean result, True if all gets deleted else false
};


message GetTagsReq {
  // left empty
}
message GetTagsRes {
  TagStruct tag = 1;
}


message AssignTagsToIdentityReq {
  repeated TagStruct tags = 1;
  string did = 2; // device identities to be tagged with
}

message AssignTagsToIdentityRes{
  bool result = 1; // true if assignment of tags to identity works; else false; default is false
}


message ListIdentitiesUnderATagReq {
  TagStruct tag = 1;
}

message ListIdentitiesUnderATagRes{
  string did = 1;
}

message GetOnboardingPkgReq {
  string identity = 1; // device's public identity
}


message  GetOnboardingPkgRes{
  string pkg1 = 1 ; //  transfers payload in string, any data structure
  bytes pkg2 = 2; // transfers payload in bytes, any data structure
}


message UploadFilesReq {
  oneof data{
    FileInfo info = 1;
    bytes chunkData = 2;
  }
  string agentPath = 3; // device path, where files will be downloaded
  string userUploadPath = 4; // upload path from the user's device
}

message DownloadFilesRes {
  oneof data{
    FileInfo info = 1;
    bytes chunkData = 2;
  }
}

message FileInfo {
  string deviceIdentity = 1;
  string fileId = 2;
  string fileType = 3;
}


message UploadFilesRes {
  bool result = 1; // true if successfully transferred the files.
}

message DownloadFilesReq {
  string deviceIdentity = 1; // device's identity
  string agentPath = 2; // agent's download path
  bool enableStaging = 3; // enable Staging
  repeated platformInternal.ArtifactHash artifactHashonAgent = 4; // artifact hash on agent
}

message FileStorePathReq {
  string deviceIdentity = 1; // device DID
  string path = 2; // folder
}
message FileStorePathRes {
  bool result = 1;
}