syntax = "proto3";
import "google/protobuf/timestamp.proto";
package release;
option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/release/v0";

message Empty {}

// Describes the type of the build/release
enum Type {
  latest = 0;
  rc = 1;
  alpha = 2;
  beta = 3;
}
// Describes the platform of the build/release
enum OSPlatform {
  unknown = 0;
  windows = 1;
  linux = 2;
  macos = 3;
  ios = 4;
  android = 5;
  darwin_amd64 = 6;
  dragonfly_amd64 = 7;
  freebsd_amd64 = 8;
  freebsd_arm5 = 9;
  freebsd_arm6 = 10;
  freebsd_arm7 = 11;
  linux_386 = 12;
  linux_amd64 = 13;
  linux_arm5 = 14;
  linux_arm64 = 15;
  linux_arm6 = 16;
  linux_arm7 = 17;
  linux_mips64le = 18;
  linux_mips64 = 19;
  linux_ppc64le = 20;
  linux_ppc64 = 21;
  netbsd_amd64 = 22;
  netbsd_arm5 = 23;
  netbsd_arm6 = 24;
  netbsd_arm7 = 25;
  openbsd_amd64 = 26;
  windows_386 = 27;
  windows_amd64 = 28;
  darwin_arm64 = 29;
}

// Describes the state of the release
// Note: DB will accept only these states in lower case; notactive is not in the
// db it is just for the UI to see null value
enum ReleaseState {
  active = 0;
  withdrawn = 1;
  outofsupport = 2;
  notactive = 3;
}

// An asset is identified by its internal ID and its external name
// E.g.: edge agent, server, app,
message Asset {
  int64 id = 1;
  string name = 2;
}

// Describes each version with separate properties to ease the use for front
// client
message Version {
  Asset assetName = 1;
  int32 year = 2;
  string version = 3;
  Type type = 4;
  string link = 5;
  OSPlatform osPlatform = 6;
  ReleaseState state = 7;
  google.protobuf.Timestamp releaseDate = 8;
}

// DownloadVersion message structure used when streaming the binary format of
// each file.
message DownloadVersion {
  oneof data {
    Release Info = 1;
    bytes ChunkData = 2;
  };
}

// CompleteReleaseZip message structure used when streaming the binary format of
// one zip file.
message CompleteReleaseZip {
  oneof data {
    string fileType = 1;
    string fileName = 2;
    bytes ChunkData = 3;
  };
}

// Release message structure
message Release {
  int64 releaseId = 1;
  string releaseName = 2; // for now this can be same as version
  google.protobuf.Timestamp releaseDate = 3;
  string releaseVersion = 4; // version e.g. v23.0.0.0, v23.0.0.1, v23.0.1.0 ,
                             // v23.0.1.0-alpha.1, v23.0.1.0-beta.2
  string releaseDescription = 5;
  google.protobuf.Timestamp releaseCreatedAt = 6;
}
// App message structure representing the Scurid App structure in the DB schema
message App {
  int64 appId = 1;            // appId is auto generated by the DB
  string appName = 2;         // appName is the name of the Scurid app
  string appBuildHash = 3;    // build hash assigned to specific build
  OSPlatform appPlatform = 4; // ENUM value for the platform
}
// Server message structure representing the Scurid Server structure in the DB
// schema
message Server {
  int64 serverId = 1;            // server_id is auto generated by the DB
  string serverName = 2;         // server_name is the name of the Scurid server
  string serverBuildHash = 3;    // build hash assigned to specific build
  OSPlatform serverPlatform = 4; // ENUM value for the platform type
}

// EdgeAgent message structure representing the Scurid Edge Agent structure in
// the DB schema
message EdgeAgent {
  int64 edgeAgentId = 1; // edge_agent_id is auto generated by the DB
  string edgeAgentName =
      2; // edge_agent_name is the name of the Scurid edge agent
  string edgeAgentBuildHash = 3;    // build hash assigned to specific build
  OSPlatform edgeAgentPlatform = 4; // ENUM value for the platform type
}

// Download message structure
// represents the download link per asset
message Download {
  string downloadLink = 1; // downloadLink is the link to download the asset
}

message ReleaseStruct {
  int64 releaseId = 1;
  string releaseName = 2;
  google.protobuf.Timestamp releaseDate = 3;
  string version = 4;
  string description = 5;
  string downloadLink = 6;
  int64 assetId = 7;
  string assetType = 8;
  string buildHash = 9;
  string assetName = 10;
  release.OSPlatform platformName = 11;
  release.ReleaseState state = 12;
}
