syntax = "proto3";
import "metadata/metadata.proto";

package storageSchemaMetadata;
option go_package = "bitbucket.org/scurid/scurid-apis/pkg/grpc/storageSchemaMetadata/v1";

service StorageSchemaMetadataService {
  rpc StoreSchemaMetadataStructure(StoreSchemaMetadataRequest) returns (StoreSchemaMetadataResponse) {
    option (metadata.v0.operationType) = WRITE;
  }
  rpc GetSchemaMetadataStructure(GetSchemaMetadataRequest) returns (GetSchemaMetadataResponse) {
    option (metadata.v0.operationType) = READ;
  }
}

message StoreSchemaMetadataRequest {
    SchemaMetadataStruct schemaMetadataStruct = 1;
}

message StoreSchemaMetadataResponse {
  bool success = 1;
}

message GetSchemaMetadataRequest {
}

message GetSchemaMetadataResponse {
  repeated SchemaMetadataStruct rows = 1;
}

message SchemaMetadataStruct {
  string alias = 1;
  string schemaMetadataStructure = 2;
  int64 createdOn = 3;
  bool isGlobal = 4;
}
