# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import edgeagent_pb2 as edgeagent__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edgeagent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScuridEdgeAgentAPIStub(object):
    """provides set of services that will be exposed as APIs for -
    Edge clients looking to interact with ScuridEdgeAgent

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDeviceIdentity = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/CreateDeviceIdentity',
                request_serializer=edgeagent__pb2.CreateDeviceIdentityReq.SerializeToString,
                response_deserializer=edgeagent__pb2.CreateDeviceIdentityRes.FromString,
                _registered_method=True)
        self.DeleteDeviceDID = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/DeleteDeviceDID',
                request_serializer=edgeagent__pb2.DeleteDeviceIdentityReq.SerializeToString,
                response_deserializer=edgeagent__pb2.DeleteDeviceIdentityRes.FromString,
                _registered_method=True)
        self.GetDeviceIdentity = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetDeviceIdentity',
                request_serializer=edgeagent__pb2.GetDeviceIdentityReq.SerializeToString,
                response_deserializer=edgeagent__pb2.GetDeviceIdentityRes.FromString,
                _registered_method=True)
        self.GetScuridEdgeAgentVersion = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetScuridEdgeAgentVersion',
                request_serializer=edgeagent__pb2.Empty.SerializeToString,
                response_deserializer=edgeagent__pb2.GetScuridEdgeAgentVersionRes.FromString,
                _registered_method=True)
        self.SignWithIdentity = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/SignWithIdentity',
                request_serializer=edgeagent__pb2.SignWithIdentityReq.SerializeToString,
                response_deserializer=edgeagent__pb2.SignWithIdentityRes.FromString,
                _registered_method=True)
        self.VerifySignature = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/VerifySignature',
                request_serializer=edgeagent__pb2.VerifySignatureReq.SerializeToString,
                response_deserializer=edgeagent__pb2.VerifySignatureRes.FromString,
                _registered_method=True)
        self.SignBytePayloadWithIdentity = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/SignBytePayloadWithIdentity',
                request_serializer=edgeagent__pb2.SignBytePayloadWithIdentityReq.SerializeToString,
                response_deserializer=edgeagent__pb2.SignBytePayloadWithIdentityRes.FromString,
                _registered_method=True)
        self.VerifyBytePayloadWithIdentity = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/VerifyBytePayloadWithIdentity',
                request_serializer=edgeagent__pb2.VerifyBytePayloadWithIdentityReq.SerializeToString,
                response_deserializer=edgeagent__pb2.VerifyBytePayloadWithIdentityRes.FromString,
                _registered_method=True)
        self.RegisterDeviceIdentity = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/RegisterDeviceIdentity',
                request_serializer=edgeagent__pb2.RegisterDeviceIdentityReq.SerializeToString,
                response_deserializer=edgeagent__pb2.RegisterDeviceIdentityRes.FromString,
                _registered_method=True)
        self.GetToken = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetToken',
                request_serializer=edgeagent__pb2.GetTokenReq.SerializeToString,
                response_deserializer=edgeagent__pb2.GetTokenRes.FromString,
                _registered_method=True)
        self.DownloadFiles = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/DownloadFiles',
                request_serializer=edgeagent__pb2.DownloadFilesReq.SerializeToString,
                response_deserializer=edgeagent__pb2.DownloadFilesRes.FromString,
                _registered_method=True)
        self.SendDeviceData = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/SendDeviceData',
                request_serializer=edgeagent__pb2.SendDeviceDataReq.SerializeToString,
                response_deserializer=edgeagent__pb2.SendDeviceDataRes.FromString,
                _registered_method=True)
        self.SendDeviceDataWithCustomFields = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/SendDeviceDataWithCustomFields',
                request_serializer=edgeagent__pb2.SendDeviceDataWithCustomFieldsReq.SerializeToString,
                response_deserializer=edgeagent__pb2.SendDeviceDataWithCustomFieldsRes.FromString,
                _registered_method=True)
        self.BiometricAuth = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/BiometricAuth',
                request_serializer=edgeagent__pb2.BiometricAuthReq.SerializeToString,
                response_deserializer=edgeagent__pb2.BiometricAuthRes.FromString,
                _registered_method=True)
        self.GetDeviceUsers = channel.unary_unary(
                '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetDeviceUsers',
                request_serializer=edgeagent__pb2.GetDeviceUsersReq.SerializeToString,
                response_deserializer=edgeagent__pb2.GetDeviceUsersRes.FromString,
                _registered_method=True)


class ScuridEdgeAgentAPIServicer(object):
    """provides set of services that will be exposed as APIs for -
    Edge clients looking to interact with ScuridEdgeAgent

    """

    def CreateDeviceIdentity(self, request, context):
        """Create an identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDeviceDID(self, request, context):
        """Delete an existing DID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceIdentity(self, request, context):
        """Validates if particular identity was already created locally
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScuridEdgeAgentVersion(self, request, context):
        """Get currently installed version of edge agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignWithIdentity(self, request, context):
        """Signs a payload with identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySignature(self, request, context):
        """Verifies a signature tagged to the payload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignBytePayloadWithIdentity(self, request, context):
        """Signs a byte array payload with identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyBytePayloadWithIdentity(self, request, context):
        """Verifies a byte array payload with identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDeviceIdentity(self, request, context):
        """To be called for registering the device identity for the first time
        Expects additional device data that will be used for binding the identity with the device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToken(self, request, context):
        """GetToken to receive required token from Scurid Platform App
        Needed in order to access APIs that need authentication from the Scurid Platform App
        Not used for authentication locally on the Scurid Edge Agent
        Also used for refreshing the token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFiles(self, request, context):
        """Used for downloading one or more files
        number of files to download will depend on files prepared by the admin on Scurid Platform App
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDeviceData(self, request, context):
        """invokes send data services within the Agent to send to the Scurid backend Server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDeviceDataWithCustomFields(self, request, context):
        """SendDeviceDataWithCustomFields this is used to send data to the Scurid backend Server with JSON formatted with custom fields
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BiometricAuth(self, request, context):
        """Initiates a human authentication with the device on which the Scurid Edge Agent is running
        before using this make sure user has enrolled biometric data with Scurid Server; if the user has never enrolled for bio-metric data, calling this API endpoint
        will not be enough. Post enrollment an administrator must grant required access rights and mapping of the user to the device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceUsers(self, request, context):
        """GetDeviceUsers returns the list of users who have access to the device
        this is the list of users who have enrolled with biometrics and have received access rights from the administrator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScuridEdgeAgentAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDeviceIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDeviceIdentity,
                    request_deserializer=edgeagent__pb2.CreateDeviceIdentityReq.FromString,
                    response_serializer=edgeagent__pb2.CreateDeviceIdentityRes.SerializeToString,
            ),
            'DeleteDeviceDID': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDeviceDID,
                    request_deserializer=edgeagent__pb2.DeleteDeviceIdentityReq.FromString,
                    response_serializer=edgeagent__pb2.DeleteDeviceIdentityRes.SerializeToString,
            ),
            'GetDeviceIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceIdentity,
                    request_deserializer=edgeagent__pb2.GetDeviceIdentityReq.FromString,
                    response_serializer=edgeagent__pb2.GetDeviceIdentityRes.SerializeToString,
            ),
            'GetScuridEdgeAgentVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScuridEdgeAgentVersion,
                    request_deserializer=edgeagent__pb2.Empty.FromString,
                    response_serializer=edgeagent__pb2.GetScuridEdgeAgentVersionRes.SerializeToString,
            ),
            'SignWithIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.SignWithIdentity,
                    request_deserializer=edgeagent__pb2.SignWithIdentityReq.FromString,
                    response_serializer=edgeagent__pb2.SignWithIdentityRes.SerializeToString,
            ),
            'VerifySignature': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySignature,
                    request_deserializer=edgeagent__pb2.VerifySignatureReq.FromString,
                    response_serializer=edgeagent__pb2.VerifySignatureRes.SerializeToString,
            ),
            'SignBytePayloadWithIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.SignBytePayloadWithIdentity,
                    request_deserializer=edgeagent__pb2.SignBytePayloadWithIdentityReq.FromString,
                    response_serializer=edgeagent__pb2.SignBytePayloadWithIdentityRes.SerializeToString,
            ),
            'VerifyBytePayloadWithIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyBytePayloadWithIdentity,
                    request_deserializer=edgeagent__pb2.VerifyBytePayloadWithIdentityReq.FromString,
                    response_serializer=edgeagent__pb2.VerifyBytePayloadWithIdentityRes.SerializeToString,
            ),
            'RegisterDeviceIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDeviceIdentity,
                    request_deserializer=edgeagent__pb2.RegisterDeviceIdentityReq.FromString,
                    response_serializer=edgeagent__pb2.RegisterDeviceIdentityRes.SerializeToString,
            ),
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=edgeagent__pb2.GetTokenReq.FromString,
                    response_serializer=edgeagent__pb2.GetTokenRes.SerializeToString,
            ),
            'DownloadFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFiles,
                    request_deserializer=edgeagent__pb2.DownloadFilesReq.FromString,
                    response_serializer=edgeagent__pb2.DownloadFilesRes.SerializeToString,
            ),
            'SendDeviceData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDeviceData,
                    request_deserializer=edgeagent__pb2.SendDeviceDataReq.FromString,
                    response_serializer=edgeagent__pb2.SendDeviceDataRes.SerializeToString,
            ),
            'SendDeviceDataWithCustomFields': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDeviceDataWithCustomFields,
                    request_deserializer=edgeagent__pb2.SendDeviceDataWithCustomFieldsReq.FromString,
                    response_serializer=edgeagent__pb2.SendDeviceDataWithCustomFieldsRes.SerializeToString,
            ),
            'BiometricAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.BiometricAuth,
                    request_deserializer=edgeagent__pb2.BiometricAuthReq.FromString,
                    response_serializer=edgeagent__pb2.BiometricAuthRes.SerializeToString,
            ),
            'GetDeviceUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceUsers,
                    request_deserializer=edgeagent__pb2.GetDeviceUsersReq.FromString,
                    response_serializer=edgeagent__pb2.GetDeviceUsersRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgeagentapis.v1.ScuridEdgeAgentAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgeagentapis.v1.ScuridEdgeAgentAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScuridEdgeAgentAPI(object):
    """provides set of services that will be exposed as APIs for -
    Edge clients looking to interact with ScuridEdgeAgent

    """

    @staticmethod
    def CreateDeviceIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/CreateDeviceIdentity',
            edgeagent__pb2.CreateDeviceIdentityReq.SerializeToString,
            edgeagent__pb2.CreateDeviceIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDeviceDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/DeleteDeviceDID',
            edgeagent__pb2.DeleteDeviceIdentityReq.SerializeToString,
            edgeagent__pb2.DeleteDeviceIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetDeviceIdentity',
            edgeagent__pb2.GetDeviceIdentityReq.SerializeToString,
            edgeagent__pb2.GetDeviceIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScuridEdgeAgentVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetScuridEdgeAgentVersion',
            edgeagent__pb2.Empty.SerializeToString,
            edgeagent__pb2.GetScuridEdgeAgentVersionRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignWithIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/SignWithIdentity',
            edgeagent__pb2.SignWithIdentityReq.SerializeToString,
            edgeagent__pb2.SignWithIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/VerifySignature',
            edgeagent__pb2.VerifySignatureReq.SerializeToString,
            edgeagent__pb2.VerifySignatureRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignBytePayloadWithIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/SignBytePayloadWithIdentity',
            edgeagent__pb2.SignBytePayloadWithIdentityReq.SerializeToString,
            edgeagent__pb2.SignBytePayloadWithIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyBytePayloadWithIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/VerifyBytePayloadWithIdentity',
            edgeagent__pb2.VerifyBytePayloadWithIdentityReq.SerializeToString,
            edgeagent__pb2.VerifyBytePayloadWithIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDeviceIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/RegisterDeviceIdentity',
            edgeagent__pb2.RegisterDeviceIdentityReq.SerializeToString,
            edgeagent__pb2.RegisterDeviceIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetToken',
            edgeagent__pb2.GetTokenReq.SerializeToString,
            edgeagent__pb2.GetTokenRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/DownloadFiles',
            edgeagent__pb2.DownloadFilesReq.SerializeToString,
            edgeagent__pb2.DownloadFilesRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDeviceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/SendDeviceData',
            edgeagent__pb2.SendDeviceDataReq.SerializeToString,
            edgeagent__pb2.SendDeviceDataRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDeviceDataWithCustomFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/SendDeviceDataWithCustomFields',
            edgeagent__pb2.SendDeviceDataWithCustomFieldsReq.SerializeToString,
            edgeagent__pb2.SendDeviceDataWithCustomFieldsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BiometricAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/BiometricAuth',
            edgeagent__pb2.BiometricAuthReq.SerializeToString,
            edgeagent__pb2.BiometricAuthRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeagentapis.v1.ScuridEdgeAgentAPI/GetDeviceUsers',
            edgeagent__pb2.GetDeviceUsersReq.SerializeToString,
            edgeagent__pb2.GetDeviceUsersRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
