# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compiled_protos.auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthStub(object):
    """Auth defines authentication service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/auth.v1.Auth/Login',
                request_serializer=auth__pb2.LoginReq.SerializeToString,
                response_deserializer=auth__pb2.LoginRes.FromString,
                _registered_method=True)
        self.SetInitialPassphrase = channel.unary_unary(
                '/auth.v1.Auth/SetInitialPassphrase',
                request_serializer=auth__pb2.SetInitialPassphraseReq.SerializeToString,
                response_deserializer=auth__pb2.SetInitialPassphraseRes.FromString,
                _registered_method=True)
        self.StoreUser = channel.unary_unary(
                '/auth.v1.Auth/StoreUser',
                request_serializer=auth__pb2.StoreUserReq.SerializeToString,
                response_deserializer=auth__pb2.StoreUserRes.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/auth.v1.Auth/RefreshToken',
                request_serializer=auth__pb2.RefreshTokenReq.SerializeToString,
                response_deserializer=auth__pb2.RefreshTokenRes.FromString,
                _registered_method=True)
        self.VerifyToken = channel.unary_unary(
                '/auth.v1.Auth/VerifyToken',
                request_serializer=auth__pb2.VerifyTokenReq.SerializeToString,
                response_deserializer=auth__pb2.VerifyTokenRes.FromString,
                _registered_method=True)


class AuthServicer(object):
    """Auth defines authentication service
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInitialPassphrase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__pb2.LoginReq.FromString,
                    response_serializer=auth__pb2.LoginRes.SerializeToString,
            ),
            'SetInitialPassphrase': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInitialPassphrase,
                    request_deserializer=auth__pb2.SetInitialPassphraseReq.FromString,
                    response_serializer=auth__pb2.SetInitialPassphraseRes.SerializeToString,
            ),
            'StoreUser': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreUser,
                    request_deserializer=auth__pb2.StoreUserReq.FromString,
                    response_serializer=auth__pb2.StoreUserRes.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth__pb2.RefreshTokenReq.FromString,
                    response_serializer=auth__pb2.RefreshTokenRes.SerializeToString,
            ),
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=auth__pb2.VerifyTokenReq.FromString,
                    response_serializer=auth__pb2.VerifyTokenRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.v1.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.v1.Auth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Auth defines authentication service
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.Auth/Login',
            auth__pb2.LoginReq.SerializeToString,
            auth__pb2.LoginRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInitialPassphrase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.Auth/SetInitialPassphrase',
            auth__pb2.SetInitialPassphraseReq.SerializeToString,
            auth__pb2.SetInitialPassphraseRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.Auth/StoreUser',
            auth__pb2.StoreUserReq.SerializeToString,
            auth__pb2.StoreUserRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.Auth/RefreshToken',
            auth__pb2.RefreshTokenReq.SerializeToString,
            auth__pb2.RefreshTokenRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.Auth/VerifyToken',
            auth__pb2.VerifyTokenReq.SerializeToString,
            auth__pb2.VerifyTokenRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
