# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
import compiled_protos.metadata.metadata_pb2 as metadata_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x07\x61uth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17metadata/metadata.proto\"T\n\x08LoginReq\x12!\n\x04user\x18\x01 \x01(\x0b\x32\x13.auth.v1.UserStruct\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x13\n\x0brequestTime\x18\x03 \x01(\x03\"/\n\nUserStruct\x12\x0f\n\x07userDID\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\x19\n\x08LoginRes\x12\r\n\x05token\x18\x01 \x01(\t\"*\n\x0cStoreUserReq\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0cStoreUserRes\x12\x0e\n\x06result\x18\x01 \x01(\x08\"-\n\x17SetInitialPassphraseReq\x12\x12\n\npassphrase\x18\x01 \x01(\t\")\n\x17SetInitialPassphraseRes\x12\x0e\n\x06result\x18\x01 \x01(\x08\"#\n\x0fRefreshTokenReq\x12\x10\n\x08oldToken\x18\x01 \x01(\t\"#\n\x0fRefreshTokenRes\x12\x10\n\x08newToken\x18\x02 \x01(\t\"\x1f\n\x0eVerifyTokenReq\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0eVerifyTokenRes\x12\x0b\n\x03res\x18\x01 \x01(\x08\x32\x92\x04\n\x04\x41uth\x12M\n\x05Login\x12\x11.auth.v1.LoginReq\x1a\x11.auth.v1.LoginRes\"\x1e\x8a\xb5\x18\x01\x01\x82\xd3\xe4\x93\x02\x13\"\x0e/v1/auth/login:\x01*\x12\x89\x01\n\x14SetInitialPassphrase\x12 .auth.v1.SetInitialPassphraseReq\x1a .auth.v1.SetInitialPassphraseRes\"-\x8a\xb5\x18\x01\x02\x82\xd3\xe4\x93\x02\"\"\x1d/v1/auth/setinitialpassphrase:\x01*\x12]\n\tStoreUser\x12\x15.auth.v1.StoreUserReq\x1a\x15.auth.v1.StoreUserRes\"\"\x8a\xb5\x18\x01\x02\x82\xd3\xe4\x93\x02\x17\"\x12/v1/auth/storeuser:\x01*\x12i\n\x0cRefreshToken\x12\x18.auth.v1.RefreshTokenReq\x1a\x18.auth.v1.RefreshTokenRes\"%\x8a\xb5\x18\x01\x01\x82\xd3\xe4\x93\x02\x1a\"\x15/v1/auth/refreshtoken:\x01*\x12\x65\n\x0bVerifyToken\x12\x17.auth.v1.VerifyTokenReq\x1a\x17.auth.v1.VerifyTokenRes\"$\x8a\xb5\x18\x01\x01\x82\xd3\xe4\x93\x02\x19\"\x14/v1/auth/verifytoken:\x01*B3Z1bitbucket.org/scurid/scurid-apis/pkg/grpc/auth/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1bitbucket.org/scurid/scurid-apis/pkg/grpc/auth/v1'
  _globals['_AUTH'].methods_by_name['Login']._loaded_options = None
  _globals['_AUTH'].methods_by_name['Login']._serialized_options = b'\212\265\030\001\001\202\323\344\223\002\023\"\016/v1/auth/login:\001*'
  _globals['_AUTH'].methods_by_name['SetInitialPassphrase']._loaded_options = None
  _globals['_AUTH'].methods_by_name['SetInitialPassphrase']._serialized_options = b'\212\265\030\001\002\202\323\344\223\002\"\"\035/v1/auth/setinitialpassphrase:\001*'
  _globals['_AUTH'].methods_by_name['StoreUser']._loaded_options = None
  _globals['_AUTH'].methods_by_name['StoreUser']._serialized_options = b'\212\265\030\001\002\202\323\344\223\002\027\"\022/v1/auth/storeuser:\001*'
  _globals['_AUTH'].methods_by_name['RefreshToken']._loaded_options = None
  _globals['_AUTH'].methods_by_name['RefreshToken']._serialized_options = b'\212\265\030\001\001\202\323\344\223\002\032\"\025/v1/auth/refreshtoken:\001*'
  _globals['_AUTH'].methods_by_name['VerifyToken']._loaded_options = None
  _globals['_AUTH'].methods_by_name['VerifyToken']._serialized_options = b'\212\265\030\001\001\202\323\344\223\002\031\"\024/v1/auth/verifytoken:\001*'
  _globals['_LOGINREQ']._serialized_start=78
  _globals['_LOGINREQ']._serialized_end=162
  _globals['_USERSTRUCT']._serialized_start=164
  _globals['_USERSTRUCT']._serialized_end=211
  _globals['_LOGINRES']._serialized_start=213
  _globals['_LOGINRES']._serialized_end=238
  _globals['_STOREUSERREQ']._serialized_start=240
  _globals['_STOREUSERREQ']._serialized_end=282
  _globals['_STOREUSERRES']._serialized_start=284
  _globals['_STOREUSERRES']._serialized_end=314
  _globals['_SETINITIALPASSPHRASEREQ']._serialized_start=316
  _globals['_SETINITIALPASSPHRASEREQ']._serialized_end=361
  _globals['_SETINITIALPASSPHRASERES']._serialized_start=363
  _globals['_SETINITIALPASSPHRASERES']._serialized_end=404
  _globals['_REFRESHTOKENREQ']._serialized_start=406
  _globals['_REFRESHTOKENREQ']._serialized_end=441
  _globals['_REFRESHTOKENRES']._serialized_start=443
  _globals['_REFRESHTOKENRES']._serialized_end=478
  _globals['_VERIFYTOKENREQ']._serialized_start=480
  _globals['_VERIFYTOKENREQ']._serialized_end=511
  _globals['_VERIFYTOKENRES']._serialized_start=513
  _globals['_VERIFYTOKENRES']._serialized_end=542
  _globals['_AUTH']._serialized_start=545
  _globals['_AUTH']._serialized_end=1075
# @@protoc_insertion_point(module_scope)
