# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import biometrics_pb2 as biometrics__pb2
from thirdParty import trustStamp_pb2 as thirdParty_dot_trustStamp__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in biometrics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BiometricsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAuthenticatedTSURL = channel.unary_stream(
                '/platformInternal.Biometrics/GetAuthenticatedTSURL',
                request_serializer=thirdParty_dot_trustStamp__pb2.InitAndAuthReq.SerializeToString,
                response_deserializer=thirdParty_dot_trustStamp__pb2.InitAndAuthRes.FromString,
                _registered_method=True)
        self.Enroll = channel.unary_unary(
                '/platformInternal.Biometrics/Enroll',
                request_serializer=biometrics__pb2.EnrollReq.SerializeToString,
                response_deserializer=biometrics__pb2.EnrollRes.FromString,
                _registered_method=True)
        self.IsAuthorised = channel.unary_stream(
                '/platformInternal.Biometrics/IsAuthorised',
                request_serializer=biometrics__pb2.IsAuthorisedReq.SerializeToString,
                response_deserializer=thirdParty_dot_trustStamp__pb2.InitAndAuthRes.FromString,
                _registered_method=True)


class BiometricsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAuthenticatedTSURL(self, request, context):
        """GetAuthenticatedTSURL wraps TrustStamp's flow/init API to get the authenticated URL with session id
        this is what the devices or clients will call to get the authenticated URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enroll(self, request, context):
        """Enroll wraps TrustStamp's enrollment API to begin the enrollment process for the user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAuthorised(self, request, context):
        """Check whether the user is authorised or not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BiometricsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAuthenticatedTSURL': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAuthenticatedTSURL,
                    request_deserializer=thirdParty_dot_trustStamp__pb2.InitAndAuthReq.FromString,
                    response_serializer=thirdParty_dot_trustStamp__pb2.InitAndAuthRes.SerializeToString,
            ),
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=biometrics__pb2.EnrollReq.FromString,
                    response_serializer=biometrics__pb2.EnrollRes.SerializeToString,
            ),
            'IsAuthorised': grpc.unary_stream_rpc_method_handler(
                    servicer.IsAuthorised,
                    request_deserializer=biometrics__pb2.IsAuthorisedReq.FromString,
                    response_serializer=thirdParty_dot_trustStamp__pb2.InitAndAuthRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platformInternal.Biometrics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('platformInternal.Biometrics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Biometrics(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAuthenticatedTSURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/platformInternal.Biometrics/GetAuthenticatedTSURL',
            thirdParty_dot_trustStamp__pb2.InitAndAuthReq.SerializeToString,
            thirdParty_dot_trustStamp__pb2.InitAndAuthRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platformInternal.Biometrics/Enroll',
            biometrics__pb2.EnrollReq.SerializeToString,
            biometrics__pb2.EnrollRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsAuthorised(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/platformInternal.Biometrics/IsAuthorised',
            biometrics__pb2.IsAuthorisedReq.SerializeToString,
            thirdParty_dot_trustStamp__pb2.InitAndAuthRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
