# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biometrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'biometrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metadata import metadata_pb2 as metadata_dot_metadata__pb2
from thirdParty import trustStamp_pb2 as thirdParty_dot_trustStamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62iometrics.proto\x12\x10platformInternal\x1a\x17metadata/metadata.proto\x1a\x1bthirdParty/trustStamp.proto\"6\n\tEnrollReq\x12)\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x17.trustStamp.v0.Customer\"O\n\tEnrollRes\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x17\n\x0fverificationURL\x18\x02 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x03 \x01(\t\"L\n\x0fIsAuthorisedReq\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x17\n\x0fverificationURL\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"!\n\x0fIsAuthorisedRes\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x92\x02\n\nBiometrics\x12^\n\x15GetAuthenticatedTSURL\x12\x1d.trustStamp.v0.InitAndAuthReq\x1a\x1d.trustStamp.v0.InitAndAuthRes\"\x05\x8a\xb5\x18\x01\x01\x30\x01\x12I\n\x06\x45nroll\x12\x1b.platformInternal.EnrollReq\x1a\x1b.platformInternal.EnrollRes\"\x05\x8a\xb5\x18\x01\x01\x12Y\n\x0cIsAuthorised\x12!.platformInternal.IsAuthorisedReq\x1a\x1d.trustStamp.v0.InitAndAuthRes\"\x05\x8a\xb5\x18\x01\x01\x30\x01\x42?Z=bitbucket.org/scurid/scurid-apis/pkg/grpc/platformInternal/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biometrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=bitbucket.org/scurid/scurid-apis/pkg/grpc/platformInternal/v1'
  _globals['_BIOMETRICS'].methods_by_name['GetAuthenticatedTSURL']._loaded_options = None
  _globals['_BIOMETRICS'].methods_by_name['GetAuthenticatedTSURL']._serialized_options = b'\212\265\030\001\001'
  _globals['_BIOMETRICS'].methods_by_name['Enroll']._loaded_options = None
  _globals['_BIOMETRICS'].methods_by_name['Enroll']._serialized_options = b'\212\265\030\001\001'
  _globals['_BIOMETRICS'].methods_by_name['IsAuthorised']._loaded_options = None
  _globals['_BIOMETRICS'].methods_by_name['IsAuthorised']._serialized_options = b'\212\265\030\001\001'
  _globals['_ENROLLREQ']._serialized_start=92
  _globals['_ENROLLREQ']._serialized_end=146
  _globals['_ENROLLRES']._serialized_start=148
  _globals['_ENROLLRES']._serialized_end=227
  _globals['_ISAUTHORISEDREQ']._serialized_start=229
  _globals['_ISAUTHORISEDREQ']._serialized_end=305
  _globals['_ISAUTHORISEDRES']._serialized_start=307
  _globals['_ISAUTHORISEDRES']._serialized_end=340
  _globals['_BIOMETRICS']._serialized_start=343
  _globals['_BIOMETRICS']._serialized_end=617
# @@protoc_insertion_point(module_scope)
