# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: certificate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'certificate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x65rtificate.proto\x12\x0e\x63\x65rtificate.v1\"%\n\x03\x43SR\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08lifetime\x18\x02 \x01(\x05\"\xb2\x01\n\tCSRCustom\x12\x12\n\ncommonName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x10\n\x08province\x18\x03 \x01(\t\x12\x10\n\x08locality\x18\x04 \x01(\t\x12\x14\n\x0corganization\x18\x05 \x01(\t\x12\x1a\n\x12organizationalUnit\x18\x06 \x01(\t\x12\x14\n\x0c\x65mailAddress\x18\x07 \x01(\t\x12\x14\n\x0clifetimeDays\x18\x08 \x01(\x05\x42:Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/certificate/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'certificate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/certificate/v1'
  _globals['_CSR']._serialized_start=37
  _globals['_CSR']._serialized_end=74
  _globals['_CSRCUSTOM']._serialized_start=77
  _globals['_CSRCUSTOM']._serialized_end=255
# @@protoc_insertion_point(module_scope)
