# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataStorageType.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dataStorageType.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x61taStorageType.proto\x12\x12\x64\x61taStorageType.v0\"\xde\x01\n\x10\x44\x61taStorageTypes\x12\x35\n\trdbmsType\x18\x01 \x01(\x0e\x32\x1d.dataStorageType.v0.RDBMSTypeH\x00\x88\x01\x01\x12\x39\n\x0bnoRdbmsType\x18\x02 \x01(\x0e\x32\x1f.dataStorageType.v0.NoRDBMSTypeH\x01\x88\x01\x01\x12:\n\x0e\x64\x65ploymentType\x18\x03 \x01(\x0e\x32\".dataStorageType.v0.DeploymentTypeB\x0c\n\n_rdbmsTypeB\x0e\n\x0c_noRdbmsType*@\n\tRDBMSType\x12\x10\n\x0cRdbmsUnknown\x10\x00\x12\x0f\n\x0b\x43ockroachDB\x10\x01\x12\x10\n\x0cPostgresqlDB\x10\x02*W\n\x0bNoRDBMSType\x12\x12\n\x0eNoRdbmsUnknown\x10\x00\x12\x0c\n\x08\x42\x61\x64gerDB\x10\x01\x12\x0b\n\x07MongoDB\x10\x02\x12\x0b\n\x07RedisDB\x10\x03\x12\x0c\n\x08InfluxDB\x10\x04*B\n\x0e\x44\x65ploymentType\x12\x19\n\x15\x44\x65ploymentTypeUnknown\x10\x00\x12\n\n\x06OnPrem\x10\x01\x12\t\n\x05\x43loud\x10\x02\x42>Z<bitbucket.org/scurid/scurid-apis/pkg/grpc/dataStorageType/v0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataStorageType_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<bitbucket.org/scurid/scurid-apis/pkg/grpc/dataStorageType/v0'
  _globals['_RDBMSTYPE']._serialized_start=270
  _globals['_RDBMSTYPE']._serialized_end=334
  _globals['_NORDBMSTYPE']._serialized_start=336
  _globals['_NORDBMSTYPE']._serialized_end=423
  _globals['_DEPLOYMENTTYPE']._serialized_start=425
  _globals['_DEPLOYMENTTYPE']._serialized_end=491
  _globals['_DATASTORAGETYPES']._serialized_start=46
  _globals['_DATASTORAGETYPES']._serialized_end=268
# @@protoc_insertion_point(module_scope)
