# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deviceContext.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'deviceContext.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x65viceContext.proto\x12\rdeviceContext\"\xa8\x01\n\rDeviceContext\x12/\n\x0cmacAddresses\x18\x01 \x03(\x0b\x32\x19.deviceContext.MacAddress\x12\x11\n\tipAddress\x18\x02 \x01(\t\x12\x0b\n\x03\x63pu\x18\x03 \x01(\t\x12\x0b\n\x03ram\x18\x04 \x01(\t\x12\x12\n\nimeiNumber\x18\x05 \x01(\t\x12%\n\x06osType\x18\x06 \x01(\x0b\x32\x15.deviceContext.OsInfo\"&\n\x06OsInfo\x12\x0e\n\x06osType\x18\x01 \x01(\t\x12\x0c\n\x04\x61rch\x18\x02 \x01(\t\";\n\nMacAddress\x12\x0b\n\x03mtu\x18\x01 \x01(\x05\x12\x12\n\nmacAddress\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\tB<Z:bitbucket.org/scurid/scurid-apis/pkg/grpc/deviceContext/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deviceContext_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:bitbucket.org/scurid/scurid-apis/pkg/grpc/deviceContext/v1'
  _globals['_DEVICECONTEXT']._serialized_start=39
  _globals['_DEVICECONTEXT']._serialized_end=207
  _globals['_OSINFO']._serialized_start=209
  _globals['_OSINFO']._serialized_end=247
  _globals['_MACADDRESS']._serialized_start=249
  _globals['_MACADDRESS']._serialized_end=308
# @@protoc_insertion_point(module_scope)
