# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: did.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'did.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdid.proto\x12\x03\x64id\"U\n\tPublicKey\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x04type\x18\x02 \x01(\x0e\x32\t.did.Type\x12\x12\n\ncontroller\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\".\n\x07Service\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fserviceEndpoint\x18\x02 \x01(\t\"\x81\x02\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x03(\t\x12&\n\x0e\x61uthentication\x18\x03 \x03(\x0b\x32\x0e.did.PublicKey\x12\x1d\n\x07service\x18\x04 \x03(\x0b\x32\x0c.did.Service\x12!\n\tpublickey\x18\x05 \x03(\x0b\x32\x0e.did.PublicKey\x12\x1f\n\x07revoked\x18\x06 \x03(\x0b\x32\x0e.did.PublicKey\x12\x0f\n\x07\x63reated\x18\x07 \x01(\x04\x12\x0f\n\x07updated\x18\x08 \x01(\x04\x12\x12\n\ncontroller\x18\t \x01(\t\x12\x17\n\x04type\x18\n \x01(\x0e\x32\t.did.Type\"I\n\x03\x44ID\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x12\n\nidentifier\x18\x02 \x01(\t\x12\x10\n\x08\x66ragment\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t*a\n\x04Type\x12\x0b\n\x07Unknown\x10\x00\x12%\n!EcdsaSecp256k1VerificationKey2019\x10\x01\x12%\n!EcdsaSecp256k1VerificationKey2018\x10\x02*\x14\n\x06Method\x12\n\n\x06scurid\x10\x00*O\n\tDIDStatus\x12\x0c\n\x08Inactive\x10\x00\x12\x0c\n\x08\x41pproved\x10\x01\x12\x0b\n\x07Pending\x10\x02\x12\x0b\n\x07Revoked\x10\x03\x12\x0c\n\x08Rejected\x10\x04\x42\x32Z0bitbucket.org/scurid/scurid-apis/pkg/grpc/did/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'did_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0bitbucket.org/scurid/scurid-apis/pkg/grpc/did/v1'
  _globals['_TYPE']._serialized_start=488
  _globals['_TYPE']._serialized_end=585
  _globals['_METHOD']._serialized_start=587
  _globals['_METHOD']._serialized_end=607
  _globals['_DIDSTATUS']._serialized_start=609
  _globals['_DIDSTATUS']._serialized_end=688
  _globals['_PUBLICKEY']._serialized_start=18
  _globals['_PUBLICKEY']._serialized_end=103
  _globals['_SERVICE']._serialized_start=105
  _globals['_SERVICE']._serialized_end=151
  _globals['_DOCUMENT']._serialized_start=154
  _globals['_DOCUMENT']._serialized_end=411
  _globals['_DID']._serialized_start=413
  _globals['_DID']._serialized_end=486
# @@protoc_insertion_point(module_scope)
