# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrastructure.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infrastructure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import certificate_pb2 as certificate__pb2
from metadata import metadata_pb2 as metadata_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14infrastructure.proto\x12\x11infrastructure.v1\x1a\x11\x63\x65rtificate.proto\x1a\x17metadata/metadata.proto\"8\n\x14\x43reateCertificateReq\x12 \n\x03\x63sr\x18\x01 \x01(\x0b\x32\x13.certificate.v1.CSR\"$\n\x14\x43reateCertificateRes\x12\x0c\n\x04\x63\x65rt\x18\x01 \x01(\x0c\x32|\n\x0c\x43\x65rtificates\x12l\n\x11\x43reateCertificate\x12\'.infrastructure.v1.CreateCertificateReq\x1a\'.infrastructure.v1.CreateCertificateRes\"\x05\x8a\xb5\x18\x01\x02\x42=Z;bitbucket.org/scurid/scurid-apis/pkg/grpc/infrastructure/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrastructure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;bitbucket.org/scurid/scurid-apis/pkg/grpc/infrastructure/v1'
  _globals['_CERTIFICATES'].methods_by_name['CreateCertificate']._loaded_options = None
  _globals['_CERTIFICATES'].methods_by_name['CreateCertificate']._serialized_options = b'\212\265\030\001\002'
  _globals['_CREATECERTIFICATEREQ']._serialized_start=87
  _globals['_CREATECERTIFICATEREQ']._serialized_end=143
  _globals['_CREATECERTIFICATERES']._serialized_start=145
  _globals['_CREATECERTIFICATERES']._serialized_end=181
  _globals['_CERTIFICATES']._serialized_start=183
  _globals['_CERTIFICATES']._serialized_end=307
# @@protoc_insertion_point(module_scope)
