# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import infrastructure_pb2 as infrastructure__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infrastructure_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CertificatesStub(object):
    """Certificates APIs designed for INTERNAL ONLY USE!!!
    Allows us to deliver variety of infrastructural features e.g. secrets, certificates etc.

    Certificates endpoint group to help create, verify, rotate certificates when needed within
    Scurid ecosystem
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCertificate = channel.unary_unary(
                '/infrastructure.v1.Certificates/CreateCertificate',
                request_serializer=infrastructure__pb2.CreateCertificateReq.SerializeToString,
                response_deserializer=infrastructure__pb2.CreateCertificateRes.FromString,
                _registered_method=True)


class CertificatesServicer(object):
    """Certificates APIs designed for INTERNAL ONLY USE!!!
    Allows us to deliver variety of infrastructural features e.g. secrets, certificates etc.

    Certificates endpoint group to help create, verify, rotate certificates when needed within
    Scurid ecosystem
    """

    def CreateCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CertificatesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCertificate,
                    request_deserializer=infrastructure__pb2.CreateCertificateReq.FromString,
                    response_serializer=infrastructure__pb2.CreateCertificateRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infrastructure.v1.Certificates', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infrastructure.v1.Certificates', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Certificates(object):
    """Certificates APIs designed for INTERNAL ONLY USE!!!
    Allows us to deliver variety of infrastructural features e.g. secrets, certificates etc.

    Certificates endpoint group to help create, verify, rotate certificates when needed within
    Scurid ecosystem
    """

    @staticmethod
    def CreateCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infrastructure.v1.Certificates/CreateCertificate',
            infrastructure__pb2.CreateCertificateReq.SerializeToString,
            infrastructure__pb2.CreateCertificateRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
