# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: integration.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'integration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import compiled_protos.certificate_pb2 as certificate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11integration.proto\x12\x0bintegration\x1a\x11\x63\x65rtificate.proto\"a\n\tThingWorx\x12\x14\n\x0cthingWorxURL\x18\x01 \x01(\t\x12\x0e\n\x06\x61ppKey\x18\x02 \x01(\t\x12.\n&useThingWorxEntityNameToDownloadAppKey\x18\x03 \x01(\x08\"A\n\x07Hawkbit\x12\x12\n\nhawkbitURL\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\":\n\x05\x41zure\x12\x1d\n\x15\x63srSigningCertificate\x18\x01 \x01(\x0c\x12\x12\n\nprivateKey\x18\x02 \x01(\x0c\"\x9f\x02\n\x12IntegrationDetails\x12\x1e\n\x16hawkbitTargetSecretKey\x18\x01 \x01(\t\x12\'\n\x1f\x64\x65viceCertificateSigningRequest\x18\x02 \x01(\t\x12\x19\n\x11\x64\x65viceCertificate\x18\x03 \x01(\x0c\x12\x39\n\x11integrationStatus\x18\x04 \x01(\x0b\x32\x1e.integration.IntegrationStatus\x12\x1f\n\x17thingworxApplicationKey\x18\x05 \x01(\t\x12\x1b\n\x13thingworxAppKeyName\x18\x06 \x01(\t\x12,\n\tcsrCustom\x18\x07 \x01(\x0b\x32\x19.certificate.v1.CSRCustom\"[\n\x11IntegrationStatus\x12\x18\n\x10thingWorxEnabled\x18\x01 \x01(\x08\x12\x16\n\x0ehawkbitEnabled\x18\x02 \x01(\x08\x12\x14\n\x0c\x61zureEnabled\x18\x03 \x01(\x08\x42:Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/integration/v0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'integration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/integration/v0'
  _globals['_THINGWORX']._serialized_start=53
  _globals['_THINGWORX']._serialized_end=150
  _globals['_HAWKBIT']._serialized_start=152
  _globals['_HAWKBIT']._serialized_end=217
  _globals['_AZURE']._serialized_start=219
  _globals['_AZURE']._serialized_end=277
  _globals['_INTEGRATIONDETAILS']._serialized_start=280
  _globals['_INTEGRATIONDETAILS']._serialized_end=567
  _globals['_INTEGRATIONSTATUS']._serialized_start=569
  _globals['_INTEGRATIONSTATUS']._serialized_end=660
# @@protoc_insertion_point(module_scope)
