# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketplace.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'marketplace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11marketplace.proto\x12\x0emarketplace.v1\"\x1a\n\x18\x45nrollForMonetizationReq\"\x1a\n\x18\x45nrollForMonetizationRes\"\x1d\n\x1bManageMarketplaceProfileReq\"\x1d\n\x1bManageMarketplaceProfileRes2\xf4\x01\n\x0bMarketplace\x12m\n\x15\x45nrollForMonetization\x12(.marketplace.v1.EnrollForMonetizationReq\x1a(.marketplace.v1.EnrollForMonetizationRes\"\x00\x12v\n\x18ManageMarketplaceProfile\x12+.marketplace.v1.ManageMarketplaceProfileReq\x1a+.marketplace.v1.ManageMarketplaceProfileRes\"\x00\x42:Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/marketplace/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marketplace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/marketplace/v1'
  _globals['_ENROLLFORMONETIZATIONREQ']._serialized_start=37
  _globals['_ENROLLFORMONETIZATIONREQ']._serialized_end=63
  _globals['_ENROLLFORMONETIZATIONRES']._serialized_start=65
  _globals['_ENROLLFORMONETIZATIONRES']._serialized_end=91
  _globals['_MANAGEMARKETPLACEPROFILEREQ']._serialized_start=93
  _globals['_MANAGEMARKETPLACEPROFILEREQ']._serialized_end=122
  _globals['_MANAGEMARKETPLACEPROFILERES']._serialized_start=124
  _globals['_MANAGEMARKETPLACEPROFILERES']._serialized_end=153
  _globals['_MARKETPLACE']._serialized_start=156
  _globals['_MARKETPLACE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
