# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import marketplace_pb2 as marketplace__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in marketplace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketplaceStub(object):
    """Marketplace : set of APIs for managing marketplace enrollment and
    To be used from the Scurid APP, or exposed to users for managing their marketplace via APIs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnrollForMonetization = channel.unary_unary(
                '/marketplace.v1.Marketplace/EnrollForMonetization',
                request_serializer=marketplace__pb2.EnrollForMonetizationReq.SerializeToString,
                response_deserializer=marketplace__pb2.EnrollForMonetizationRes.FromString,
                _registered_method=True)
        self.ManageMarketplaceProfile = channel.unary_unary(
                '/marketplace.v1.Marketplace/ManageMarketplaceProfile',
                request_serializer=marketplace__pb2.ManageMarketplaceProfileReq.SerializeToString,
                response_deserializer=marketplace__pb2.ManageMarketplaceProfileRes.FromString,
                _registered_method=True)


class MarketplaceServicer(object):
    """Marketplace : set of APIs for managing marketplace enrollment and
    To be used from the Scurid APP, or exposed to users for managing their marketplace via APIs
    """

    def EnrollForMonetization(self, request, context):
        """EnrollForMonetization enables monetization on variety of datasets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageMarketplaceProfile(self, request, context):
        """ManageMarketplaceProfile manage the user's profile for marketplace, different
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketplaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnrollForMonetization': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollForMonetization,
                    request_deserializer=marketplace__pb2.EnrollForMonetizationReq.FromString,
                    response_serializer=marketplace__pb2.EnrollForMonetizationRes.SerializeToString,
            ),
            'ManageMarketplaceProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageMarketplaceProfile,
                    request_deserializer=marketplace__pb2.ManageMarketplaceProfileReq.FromString,
                    response_serializer=marketplace__pb2.ManageMarketplaceProfileRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.v1.Marketplace', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.v1.Marketplace', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Marketplace(object):
    """Marketplace : set of APIs for managing marketplace enrollment and
    To be used from the Scurid APP, or exposed to users for managing their marketplace via APIs
    """

    @staticmethod
    def EnrollForMonetization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.v1.Marketplace/EnrollForMonetization',
            marketplace__pb2.EnrollForMonetizationReq.SerializeToString,
            marketplace__pb2.EnrollForMonetizationRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageMarketplaceProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.v1.Marketplace/ManageMarketplaceProfile',
            marketplace__pb2.ManageMarketplaceProfileReq.SerializeToString,
            marketplace__pb2.ManageMarketplaceProfileRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
