# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import compiled_protos.platformapiv2_pb2 as platformapiv2__pb2


class PlatformStub(object):
    """This API is to be used by :
    * Scurid Edge Agent when attempting to communicate with Scurid SSI Service, as edge agents will usually not connect to the SSI Service, therefore ScuridPlatformAgentAPI works as a central administration hub for customers to manage their devices
    * Desktop apps
    * Custom application
    This is the v2 of the platform api and will only contain new & breaking changes to the platformapi.proto to be backward compatible.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentityInfo = channel.unary_unary(
                '/platform.v2.Platform/GetIdentityInfo',
                request_serializer=platformapiv2__pb2.GetIdentityInfoReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.GetIdentityInfoRes.FromString,
                )
        self.GetAgentsList = channel.unary_unary(
                '/platform.v2.Platform/GetAgentsList',
                request_serializer=platformapiv2__pb2.GetAgentsListReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.GetAgentsListRes.FromString,
                )
        self.GetAgentInfo = channel.unary_unary(
                '/platform.v2.Platform/GetAgentInfo',
                request_serializer=platformapiv2__pb2.GetAgentInfoReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.GetAgentInfoRes.FromString,
                )
        self.RegisterAgent = channel.unary_unary(
                '/platform.v2.Platform/RegisterAgent',
                request_serializer=platformapiv2__pb2.RegisterAgentReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.RegisterAgentRes.FromString,
                )
        self.RevokeAgent = channel.unary_unary(
                '/platform.v2.Platform/RevokeAgent',
                request_serializer=platformapiv2__pb2.RevokeAgentReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.RevokeAgentRes.FromString,
                )
        self.VerifyAgent = channel.unary_unary(
                '/platform.v2.Platform/VerifyAgent',
                request_serializer=platformapiv2__pb2.VerifyAgentReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.VerifyAgentRes.FromString,
                )
        self.ConfigureAgent = channel.unary_unary(
                '/platform.v2.Platform/ConfigureAgent',
                request_serializer=platformapiv2__pb2.ConfigureAgentReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.ConfigureAgentRes.FromString,
                )


class PlatformServicer(object):
    """This API is to be used by :
    * Scurid Edge Agent when attempting to communicate with Scurid SSI Service, as edge agents will usually not connect to the SSI Service, therefore ScuridPlatformAgentAPI works as a central administration hub for customers to manage their devices
    * Desktop apps
    * Custom application
    This is the v2 of the platform api and will only contain new & breaking changes to the platformapi.proto to be backward compatible.

    """

    def GetIdentityInfo(self, request, context):
        """Fetches details available on a given identity in local DB storage
        it can be used for any kind of identity i.e.approved, rejected or pending
        GetIdentityInfo is currently under development do not use //
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentsList(self, request, context):
        """GetAgentsList returns list of all agents along with their details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentInfo(self, request, context):
        """GetAgentInfo returns detail about individual agent identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """RegisterAgent approves a pending agent in the system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAgent(self, request, context):
        """RevokeAgent revokes an agent's identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyAgent(self, request, context):
        """VerifyAgent verifies agent's authenticity against the Scurid SSI service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureAgent(self, request, context):
        """ConfigureAgent helps modify Scurid Edge Agent behaviour
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentityInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentityInfo,
                    request_deserializer=platformapiv2__pb2.GetIdentityInfoReq.FromString,
                    response_serializer=platformapiv2__pb2.GetIdentityInfoRes.SerializeToString,
            ),
            'GetAgentsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentsList,
                    request_deserializer=platformapiv2__pb2.GetAgentsListReq.FromString,
                    response_serializer=platformapiv2__pb2.GetAgentsListRes.SerializeToString,
            ),
            'GetAgentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentInfo,
                    request_deserializer=platformapiv2__pb2.GetAgentInfoReq.FromString,
                    response_serializer=platformapiv2__pb2.GetAgentInfoRes.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=platformapiv2__pb2.RegisterAgentReq.FromString,
                    response_serializer=platformapiv2__pb2.RegisterAgentRes.SerializeToString,
            ),
            'RevokeAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAgent,
                    request_deserializer=platformapiv2__pb2.RevokeAgentReq.FromString,
                    response_serializer=platformapiv2__pb2.RevokeAgentRes.SerializeToString,
            ),
            'VerifyAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAgent,
                    request_deserializer=platformapiv2__pb2.VerifyAgentReq.FromString,
                    response_serializer=platformapiv2__pb2.VerifyAgentRes.SerializeToString,
            ),
            'ConfigureAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureAgent,
                    request_deserializer=platformapiv2__pb2.ConfigureAgentReq.FromString,
                    response_serializer=platformapiv2__pb2.ConfigureAgentRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platform.v2.Platform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Platform(object):
    """This API is to be used by :
    * Scurid Edge Agent when attempting to communicate with Scurid SSI Service, as edge agents will usually not connect to the SSI Service, therefore ScuridPlatformAgentAPI works as a central administration hub for customers to manage their devices
    * Desktop apps
    * Custom application
    This is the v2 of the platform api and will only contain new & breaking changes to the platformapi.proto to be backward compatible.

    """

    @staticmethod
    def GetIdentityInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Platform/GetIdentityInfo',
            platformapiv2__pb2.GetIdentityInfoReq.SerializeToString,
            platformapiv2__pb2.GetIdentityInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Platform/GetAgentsList',
            platformapiv2__pb2.GetAgentsListReq.SerializeToString,
            platformapiv2__pb2.GetAgentsListRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Platform/GetAgentInfo',
            platformapiv2__pb2.GetAgentInfoReq.SerializeToString,
            platformapiv2__pb2.GetAgentInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Platform/RegisterAgent',
            platformapiv2__pb2.RegisterAgentReq.SerializeToString,
            platformapiv2__pb2.RegisterAgentRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Platform/RevokeAgent',
            platformapiv2__pb2.RevokeAgentReq.SerializeToString,
            platformapiv2__pb2.RevokeAgentRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Platform/VerifyAgent',
            platformapiv2__pb2.VerifyAgentReq.SerializeToString,
            platformapiv2__pb2.VerifyAgentRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Platform/ConfigureAgent',
            platformapiv2__pb2.ConfigureAgentReq.SerializeToString,
            platformapiv2__pb2.ConfigureAgentRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SubsystemsStub(object):
    """Provides configuration possibilities for different components in the system
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIDSettings = channel.unary_unary(
                '/platform.v2.Subsystems/GetIDSettings',
                request_serializer=platformapiv2__pb2.GetIDSettingsReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.GetIDSettingsRes.FromString,
                )
        self.SetIDSettings = channel.unary_unary(
                '/platform.v2.Subsystems/SetIDSettings',
                request_serializer=platformapiv2__pb2.SetIDSettingsReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.SetIDSettingsRes.FromString,
                )
        self.GetIdentityLog = channel.unary_stream(
                '/platform.v2.Subsystems/GetIdentityLog',
                request_serializer=platformapiv2__pb2.GetIdentityLogReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.GetIdentityLogRes.FromString,
                )
        self.RecordAppLogs = channel.unary_unary(
                '/platform.v2.Subsystems/RecordAppLogs',
                request_serializer=platformapiv2__pb2.RecordAppLogsReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.RecordAppLogsRes.FromString,
                )
        self.GetAppLogs = channel.unary_stream(
                '/platform.v2.Subsystems/GetAppLogs',
                request_serializer=platformapiv2__pb2.GetAppLogsReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.GetAppLogsRes.FromString,
                )
        self.StoreIntegrationConfig = channel.unary_unary(
                '/platform.v2.Subsystems/StoreIntegrationConfig',
                request_serializer=platformapiv2__pb2.StoreIntegrationConfigReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.StoreIntegrationConfigRes.FromString,
                )
        self.GetIntegrationConfig = channel.unary_unary(
                '/platform.v2.Subsystems/GetIntegrationConfig',
                request_serializer=platformapiv2__pb2.GetIntegrationConfigReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.GetIntegrationConfigRes.FromString,
                )


class SubsystemsServicer(object):
    """Provides configuration possibilities for different components in the system
    """

    def GetIDSettings(self, request, context):
        """GetIDSettings gets currently stored settings about IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIDSettings(self, request, context):
        """SetIDSettings sets up different settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdentityLog(self, request, context):
        """GetIdentityLog provides list of log recorded on activities performed on identities. This covers both agent and non agent identities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordAppLogs(self, request, context):
        """RecordAppLogs records Scurid App logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppLogs(self, request, context):
        """GetAppLogs fetches app log persisted as history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreIntegrationConfig(self, request, context):
        """Stores Integration configuration in Scurid Server storage
        This is a global configuration and will be used by all identities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegrationConfig(self, request, context):
        """GetIntegrationConfig fetches currently stored integration configuration from Scurid Server
        This is a global configuration and will be used by all identities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubsystemsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIDSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIDSettings,
                    request_deserializer=platformapiv2__pb2.GetIDSettingsReq.FromString,
                    response_serializer=platformapiv2__pb2.GetIDSettingsRes.SerializeToString,
            ),
            'SetIDSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIDSettings,
                    request_deserializer=platformapiv2__pb2.SetIDSettingsReq.FromString,
                    response_serializer=platformapiv2__pb2.SetIDSettingsRes.SerializeToString,
            ),
            'GetIdentityLog': grpc.unary_stream_rpc_method_handler(
                    servicer.GetIdentityLog,
                    request_deserializer=platformapiv2__pb2.GetIdentityLogReq.FromString,
                    response_serializer=platformapiv2__pb2.GetIdentityLogRes.SerializeToString,
            ),
            'RecordAppLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordAppLogs,
                    request_deserializer=platformapiv2__pb2.RecordAppLogsReq.FromString,
                    response_serializer=platformapiv2__pb2.RecordAppLogsRes.SerializeToString,
            ),
            'GetAppLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAppLogs,
                    request_deserializer=platformapiv2__pb2.GetAppLogsReq.FromString,
                    response_serializer=platformapiv2__pb2.GetAppLogsRes.SerializeToString,
            ),
            'StoreIntegrationConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreIntegrationConfig,
                    request_deserializer=platformapiv2__pb2.StoreIntegrationConfigReq.FromString,
                    response_serializer=platformapiv2__pb2.StoreIntegrationConfigRes.SerializeToString,
            ),
            'GetIntegrationConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrationConfig,
                    request_deserializer=platformapiv2__pb2.GetIntegrationConfigReq.FromString,
                    response_serializer=platformapiv2__pb2.GetIntegrationConfigRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platform.v2.Subsystems', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Subsystems(object):
    """Provides configuration possibilities for different components in the system
    """

    @staticmethod
    def GetIDSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Subsystems/GetIDSettings',
            platformapiv2__pb2.GetIDSettingsReq.SerializeToString,
            platformapiv2__pb2.GetIDSettingsRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetIDSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Subsystems/SetIDSettings',
            platformapiv2__pb2.SetIDSettingsReq.SerializeToString,
            platformapiv2__pb2.SetIDSettingsRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIdentityLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/platform.v2.Subsystems/GetIdentityLog',
            platformapiv2__pb2.GetIdentityLogReq.SerializeToString,
            platformapiv2__pb2.GetIdentityLogRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecordAppLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Subsystems/RecordAppLogs',
            platformapiv2__pb2.RecordAppLogsReq.SerializeToString,
            platformapiv2__pb2.RecordAppLogsRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAppLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/platform.v2.Subsystems/GetAppLogs',
            platformapiv2__pb2.GetAppLogsReq.SerializeToString,
            platformapiv2__pb2.GetAppLogsRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StoreIntegrationConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Subsystems/StoreIntegrationConfig',
            platformapiv2__pb2.StoreIntegrationConfigReq.SerializeToString,
            platformapiv2__pb2.StoreIntegrationConfigRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIntegrationConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform.v2.Subsystems/GetIntegrationConfig',
            platformapiv2__pb2.GetIntegrationConfigReq.SerializeToString,
            platformapiv2__pb2.GetIntegrationConfigRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
