# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compiled_protos.platformapi_pb2 as platformapi__pb2
import compiled_protos.platformapiv2_pb2 as platformapiv2__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in platformapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScuridPlatformAgentAPIStub(object):
    """This API is to be used by :
    * Scurid Edge Agent when attempting to communicate with Scurid SSI Service, as edge agents will usually not connect to the SSI Service, therefore ScuridPlatformAgentAPI works as a central administration hub for customers to manage their devices
    * Desktop apps

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPendingRequestsList = channel.unary_stream(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetPendingRequestsList',
                request_serializer=platformapi__pb2.GetPendingRequestsListReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetPendingRequestsListRes.FromString,
                _registered_method=True)
        self.VerifySignature = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/VerifySignature',
                request_serializer=platformapi__pb2.VerifySignatureReq.SerializeToString,
                response_deserializer=platformapi__pb2.VerifySignatureRes.FromString,
                _registered_method=True)
        self.CreateIdentity = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/CreateIdentity',
                request_serializer=platformapi__pb2.CreateIdentityReq.SerializeToString,
                response_deserializer=platformapi__pb2.CreateIdentityRes.FromString,
                _registered_method=True)
        self.SignPayload = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/SignPayload',
                request_serializer=platformapi__pb2.SignPayloadReq.SerializeToString,
                response_deserializer=platformapi__pb2.SignPayloadRes.FromString,
                _registered_method=True)
        self.GetRejectedIdentitiesList = channel.unary_stream(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetRejectedIdentitiesList',
                request_serializer=platformapi__pb2.GetRejectedIdentitiesListReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetRejectedIdentitiesListRes.FromString,
                _registered_method=True)
        self.GetValidIdentitiesList = channel.unary_stream(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetValidIdentitiesList',
                request_serializer=platformapi__pb2.GetValidIdentitiesListReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetValidIdentitiesListRes.FromString,
                _registered_method=True)
        self.GetValidIdentityInfo = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetValidIdentityInfo',
                request_serializer=platformapi__pb2.GetValidIdentityInfoReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetValidIdentityInfoRes.FromString,
                _registered_method=True)
        self.RecordRejectedDID = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RecordRejectedDID',
                request_serializer=platformapi__pb2.RecordRejectedDIDReq.SerializeToString,
                response_deserializer=platformapi__pb2.RecordRejectedDIDRes.FromString,
                _registered_method=True)
        self.RequestRegistrationOfDevice = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RequestRegistrationOfDevice',
                request_serializer=platformapi__pb2.RequestRegistrationOfDeviceReq.SerializeToString,
                response_deserializer=platformapi__pb2.RequestRegistrationOfDeviceRes.FromString,
                _registered_method=True)
        self.RequestIdentityStatus = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RequestIdentityStatus',
                request_serializer=platformapi__pb2.RequestIdentityStatusReq.SerializeToString,
                response_deserializer=platformapi__pb2.RequestIdentityStatusRes.FromString,
                _registered_method=True)
        self.LocalStorageInit = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/LocalStorageInit',
                request_serializer=platformapi__pb2.LocalStorageInitReq.SerializeToString,
                response_deserializer=platformapi__pb2.LocalStorageInitRes.FromString,
                _registered_method=True)
        self.GetAllDevicesList = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetAllDevicesList',
                request_serializer=platformapi__pb2.GetAllDevicesListReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetAllDevicesListRes.FromString,
                _registered_method=True)
        self.VerifyDeviceDID = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/VerifyDeviceDID',
                request_serializer=platformapi__pb2.VerifyDeviceDIDReq.SerializeToString,
                response_deserializer=platformapi__pb2.VerifyDeviceDIDRes.FromString,
                _registered_method=True)
        self.RevokeDeviceDID = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RevokeDeviceDID',
                request_serializer=platformapi__pb2.RevokeDeviceDIDReq.SerializeToString,
                response_deserializer=platformapi__pb2.RevokeDeviceDIDRes.FromString,
                _registered_method=True)
        self.RegisterDeviceDID = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RegisterDeviceDID',
                request_serializer=platformapi__pb2.RegisterDeviceDIDReq.SerializeToString,
                response_deserializer=platformapi__pb2.RegisterDeviceDIDRes.FromString,
                _registered_method=True)
        self.GetPlatformDID = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetPlatformDID',
                request_serializer=platformapi__pb2.GetPlatformDIDReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetPlatformDIDRes.FromString,
                _registered_method=True)
        self.GetDevicePayloadsWithSignature = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetDevicePayloadsWithSignature',
                request_serializer=platformapi__pb2.GetDevicePayloadsWithSignatureReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetDevicePayloadsWithSignatureRes.FromString,
                _registered_method=True)
        self.PostDeviceDataWithSignature = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/PostDeviceDataWithSignature',
                request_serializer=platformapi__pb2.PostDeviceDataWithSignatureReq.SerializeToString,
                response_deserializer=platformapi__pb2.PostDeviceDataWithSignatureRes.FromString,
                _registered_method=True)
        self.GetCountriesList = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetCountriesList',
                request_serializer=platformapi__pb2.GetCountriesListReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetCountriesListRes.FromString,
                _registered_method=True)
        self.GetLicenseStatus = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetLicenseStatus',
                request_serializer=platformapi__pb2.GetLicenseStatusReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetLicenseStatusRes.FromString,
                _registered_method=True)
        self.SignBytePayloadWithIdentity = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/SignBytePayloadWithIdentity',
                request_serializer=platformapi__pb2.SignBytePayloadWithIdentityReq.SerializeToString,
                response_deserializer=platformapi__pb2.SignBytePayloadWithIdentityRes.FromString,
                _registered_method=True)
        self.VerifyBytePayloadWithIdentity = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/VerifyBytePayloadWithIdentity',
                request_serializer=platformapi__pb2.VerifyBytePayloadWithIdentityReq.SerializeToString,
                response_deserializer=platformapi__pb2.VerifyBytePayloadWithIdentityRes.FromString,
                _registered_method=True)
        self.AddTags = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/AddTags',
                request_serializer=platformapi__pb2.AddTagsReq.SerializeToString,
                response_deserializer=platformapi__pb2.AddTagsRes.FromString,
                _registered_method=True)
        self.RemoveTags = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RemoveTags',
                request_serializer=platformapi__pb2.RemoveTagsReq.SerializeToString,
                response_deserializer=platformapi__pb2.RemoveTagsRes.FromString,
                _registered_method=True)
        self.GetTags = channel.unary_stream(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetTags',
                request_serializer=platformapi__pb2.GetTagsReq.SerializeToString,
                response_deserializer=platformapi__pb2.GetTagsRes.FromString,
                _registered_method=True)
        self.AssignTagsToIdentity = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/AssignTagsToIdentity',
                request_serializer=platformapi__pb2.AssignTagsToIdentityReq.SerializeToString,
                response_deserializer=platformapi__pb2.AssignTagsToIdentityRes.FromString,
                _registered_method=True)
        self.ListIdentitiesUnderATag = channel.unary_stream(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/ListIdentitiesUnderATag',
                request_serializer=platformapi__pb2.ListIdentitiesUnderATagReq.SerializeToString,
                response_deserializer=platformapi__pb2.ListIdentitiesUnderATagRes.FromString,
                _registered_method=True)
        self.UploadFiles = channel.stream_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/UploadFiles',
                request_serializer=platformapi__pb2.UploadFilesReq.SerializeToString,
                response_deserializer=platformapi__pb2.UploadFilesRes.FromString,
                _registered_method=True)
        self.DownloadFiles = channel.unary_stream(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/DownloadFiles',
                request_serializer=platformapi__pb2.DownloadFilesReq.SerializeToString,
                response_deserializer=platformapi__pb2.DownloadFilesRes.FromString,
                _registered_method=True)
        self.FileStorePath = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/FileStorePath',
                request_serializer=platformapi__pb2.FileStorePathReq.SerializeToString,
                response_deserializer=platformapi__pb2.FileStorePathRes.FromString,
                _registered_method=True)
        self.RecordAppLogs = channel.unary_unary(
                '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RecordAppLogs',
                request_serializer=platformapiv2__pb2.RecordAppLogsReq.SerializeToString,
                response_deserializer=platformapiv2__pb2.RecordAppLogsRes.FromString,
                _registered_method=True)


class ScuridPlatformAgentAPIServicer(object):
    """This API is to be used by :
    * Scurid Edge Agent when attempting to communicate with Scurid SSI Service, as edge agents will usually not connect to the SSI Service, therefore ScuridPlatformAgentAPI works as a central administration hub for customers to manage their devices
    * Desktop apps

    """

    def GetPendingRequestsList(self, request, context):
        """Track requests from new devices to register them on the SSI Service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySignature(self, request, context):
        """Verify signature of the payload
        Currently only string payloads are supported
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIdentity(self, request, context):
        """Primarily to be used for DID Generation of the platform to be used for registering platform application for that customer
        This should make an internal call to the Scurid SSI Service and store the DID value in local storage in encrypted wallet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignPayload(self, request, context):
        """Sign a given payload with platform's DID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRejectedIdentitiesList(self, request, context):
        """As platform agent must track every incoming request for DID registration in local DB storage, this service returns the list of all the DIDs that were rejected by the customer to be registered with Scurid SSI Service. This is mainly a bookkeeping service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidIdentitiesList(self, request, context):
        """Fetches the list of all the DIDs that were successfully registered in Scurid SSI Service, this list must be kept internally fresh by the platform's internal service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidIdentityInfo(self, request, context):
        """Fetches details available on a given identity in local DB storage, data on this identity must be kept fresh by internal services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordRejectedDID(self, request, context):
        """Identities returned by GetPendingRequestsList if they are rejected by the customer from the flutter app, they of course MUST not be registered with Scurid SSI Service, but at the same time should be recorded in the local DB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRegistrationOfDevice(self, request, context):
        """this endpoint is for devices to call Platform Agent to register them
        Normally will be used by devices wanting to registering for the first time, or if a new DID has been generated on an existing device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestIdentityStatus(self, request, context):
        """This endpoint is primarily meant for devices to get validation from Platform Application
        if their DID was registered on the blockchain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalStorageInit(self, request, context):
        """To be called from desktop app for getting the path where DB should be initialized
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllDevicesList(self, request, context):
        """A call to local storage to get list of all available device DIDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyDeviceDID(self, request, context):
        """Wraps the call for SSI Service API with same name VerifyDeviceDID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeDeviceDID(self, request, context):
        """Wraps the call for SSI Service API with same name RevokeDeviceDID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDeviceDID(self, request, context):
        """Wraps the call for SSI Service API with same name RegisterDeviceDID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatformDID(self, request, context):
        """To provide Platform DID from the local gRPC platform storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevicePayloadsWithSignature(self, request, context):
        """Provides device's data with signature for each payload
        returned rows have boolean confirmation attached to each row
        True denotes that the device's payload has valid signature, false denotes otherwise
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostDeviceDataWithSignature(self, request, context):
        """PostDeviceDataWithSignature to be called from edge devices to post / send their device data with signature to Platform
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCountriesList(self, request, context):
        """Provides list of countries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLicenseStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignBytePayloadWithIdentity(self, request, context):
        """Signs a byte array payload with identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyBytePayloadWithIdentity(self, request, context):
        """Verifies a byte array payload with identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTags(self, request, context):
        """Adds tags for categorization of the identities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTags(self, request, context):
        """Removes existing tags from the identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTags(self, request, context):
        """Get existing tags
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTagsToIdentity(self, request, context):
        """AssignTagsToIdentity assign one more tags to an identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIdentitiesUnderATag(self, request, context):
        """Lists all the identities assigned to a Tag
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFiles(self, request_iterator, context):
        """Used for uploading files to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFiles(self, request, context):
        """Used for downloading device pkgs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileStorePath(self, request, context):
        """FileStorePath provides path for the device files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordAppLogs(self, request, context):
        """RecordAppLogs records Scurid App logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScuridPlatformAgentAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPendingRequestsList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPendingRequestsList,
                    request_deserializer=platformapi__pb2.GetPendingRequestsListReq.FromString,
                    response_serializer=platformapi__pb2.GetPendingRequestsListRes.SerializeToString,
            ),
            'VerifySignature': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySignature,
                    request_deserializer=platformapi__pb2.VerifySignatureReq.FromString,
                    response_serializer=platformapi__pb2.VerifySignatureRes.SerializeToString,
            ),
            'CreateIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIdentity,
                    request_deserializer=platformapi__pb2.CreateIdentityReq.FromString,
                    response_serializer=platformapi__pb2.CreateIdentityRes.SerializeToString,
            ),
            'SignPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.SignPayload,
                    request_deserializer=platformapi__pb2.SignPayloadReq.FromString,
                    response_serializer=platformapi__pb2.SignPayloadRes.SerializeToString,
            ),
            'GetRejectedIdentitiesList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRejectedIdentitiesList,
                    request_deserializer=platformapi__pb2.GetRejectedIdentitiesListReq.FromString,
                    response_serializer=platformapi__pb2.GetRejectedIdentitiesListRes.SerializeToString,
            ),
            'GetValidIdentitiesList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetValidIdentitiesList,
                    request_deserializer=platformapi__pb2.GetValidIdentitiesListReq.FromString,
                    response_serializer=platformapi__pb2.GetValidIdentitiesListRes.SerializeToString,
            ),
            'GetValidIdentityInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValidIdentityInfo,
                    request_deserializer=platformapi__pb2.GetValidIdentityInfoReq.FromString,
                    response_serializer=platformapi__pb2.GetValidIdentityInfoRes.SerializeToString,
            ),
            'RecordRejectedDID': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordRejectedDID,
                    request_deserializer=platformapi__pb2.RecordRejectedDIDReq.FromString,
                    response_serializer=platformapi__pb2.RecordRejectedDIDRes.SerializeToString,
            ),
            'RequestRegistrationOfDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRegistrationOfDevice,
                    request_deserializer=platformapi__pb2.RequestRegistrationOfDeviceReq.FromString,
                    response_serializer=platformapi__pb2.RequestRegistrationOfDeviceRes.SerializeToString,
            ),
            'RequestIdentityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestIdentityStatus,
                    request_deserializer=platformapi__pb2.RequestIdentityStatusReq.FromString,
                    response_serializer=platformapi__pb2.RequestIdentityStatusRes.SerializeToString,
            ),
            'LocalStorageInit': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalStorageInit,
                    request_deserializer=platformapi__pb2.LocalStorageInitReq.FromString,
                    response_serializer=platformapi__pb2.LocalStorageInitRes.SerializeToString,
            ),
            'GetAllDevicesList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllDevicesList,
                    request_deserializer=platformapi__pb2.GetAllDevicesListReq.FromString,
                    response_serializer=platformapi__pb2.GetAllDevicesListRes.SerializeToString,
            ),
            'VerifyDeviceDID': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDeviceDID,
                    request_deserializer=platformapi__pb2.VerifyDeviceDIDReq.FromString,
                    response_serializer=platformapi__pb2.VerifyDeviceDIDRes.SerializeToString,
            ),
            'RevokeDeviceDID': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeDeviceDID,
                    request_deserializer=platformapi__pb2.RevokeDeviceDIDReq.FromString,
                    response_serializer=platformapi__pb2.RevokeDeviceDIDRes.SerializeToString,
            ),
            'RegisterDeviceDID': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDeviceDID,
                    request_deserializer=platformapi__pb2.RegisterDeviceDIDReq.FromString,
                    response_serializer=platformapi__pb2.RegisterDeviceDIDRes.SerializeToString,
            ),
            'GetPlatformDID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatformDID,
                    request_deserializer=platformapi__pb2.GetPlatformDIDReq.FromString,
                    response_serializer=platformapi__pb2.GetPlatformDIDRes.SerializeToString,
            ),
            'GetDevicePayloadsWithSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevicePayloadsWithSignature,
                    request_deserializer=platformapi__pb2.GetDevicePayloadsWithSignatureReq.FromString,
                    response_serializer=platformapi__pb2.GetDevicePayloadsWithSignatureRes.SerializeToString,
            ),
            'PostDeviceDataWithSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.PostDeviceDataWithSignature,
                    request_deserializer=platformapi__pb2.PostDeviceDataWithSignatureReq.FromString,
                    response_serializer=platformapi__pb2.PostDeviceDataWithSignatureRes.SerializeToString,
            ),
            'GetCountriesList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCountriesList,
                    request_deserializer=platformapi__pb2.GetCountriesListReq.FromString,
                    response_serializer=platformapi__pb2.GetCountriesListRes.SerializeToString,
            ),
            'GetLicenseStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLicenseStatus,
                    request_deserializer=platformapi__pb2.GetLicenseStatusReq.FromString,
                    response_serializer=platformapi__pb2.GetLicenseStatusRes.SerializeToString,
            ),
            'SignBytePayloadWithIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.SignBytePayloadWithIdentity,
                    request_deserializer=platformapi__pb2.SignBytePayloadWithIdentityReq.FromString,
                    response_serializer=platformapi__pb2.SignBytePayloadWithIdentityRes.SerializeToString,
            ),
            'VerifyBytePayloadWithIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyBytePayloadWithIdentity,
                    request_deserializer=platformapi__pb2.VerifyBytePayloadWithIdentityReq.FromString,
                    response_serializer=platformapi__pb2.VerifyBytePayloadWithIdentityRes.SerializeToString,
            ),
            'AddTags': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTags,
                    request_deserializer=platformapi__pb2.AddTagsReq.FromString,
                    response_serializer=platformapi__pb2.AddTagsRes.SerializeToString,
            ),
            'RemoveTags': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTags,
                    request_deserializer=platformapi__pb2.RemoveTagsReq.FromString,
                    response_serializer=platformapi__pb2.RemoveTagsRes.SerializeToString,
            ),
            'GetTags': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTags,
                    request_deserializer=platformapi__pb2.GetTagsReq.FromString,
                    response_serializer=platformapi__pb2.GetTagsRes.SerializeToString,
            ),
            'AssignTagsToIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTagsToIdentity,
                    request_deserializer=platformapi__pb2.AssignTagsToIdentityReq.FromString,
                    response_serializer=platformapi__pb2.AssignTagsToIdentityRes.SerializeToString,
            ),
            'ListIdentitiesUnderATag': grpc.unary_stream_rpc_method_handler(
                    servicer.ListIdentitiesUnderATag,
                    request_deserializer=platformapi__pb2.ListIdentitiesUnderATagReq.FromString,
                    response_serializer=platformapi__pb2.ListIdentitiesUnderATagRes.SerializeToString,
            ),
            'UploadFiles': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFiles,
                    request_deserializer=platformapi__pb2.UploadFilesReq.FromString,
                    response_serializer=platformapi__pb2.UploadFilesRes.SerializeToString,
            ),
            'DownloadFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFiles,
                    request_deserializer=platformapi__pb2.DownloadFilesReq.FromString,
                    response_serializer=platformapi__pb2.DownloadFilesRes.SerializeToString,
            ),
            'FileStorePath': grpc.unary_unary_rpc_method_handler(
                    servicer.FileStorePath,
                    request_deserializer=platformapi__pb2.FileStorePathReq.FromString,
                    response_serializer=platformapi__pb2.FileStorePathRes.SerializeToString,
            ),
            'RecordAppLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordAppLogs,
                    request_deserializer=platformapiv2__pb2.RecordAppLogsReq.FromString,
                    response_serializer=platformapiv2__pb2.RecordAppLogsRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scuridplatformagentapi.v1.ScuridPlatformAgentAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scuridplatformagentapi.v1.ScuridPlatformAgentAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScuridPlatformAgentAPI(object):
    """This API is to be used by :
    * Scurid Edge Agent when attempting to communicate with Scurid SSI Service, as edge agents will usually not connect to the SSI Service, therefore ScuridPlatformAgentAPI works as a central administration hub for customers to manage their devices
    * Desktop apps

    """

    @staticmethod
    def GetPendingRequestsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetPendingRequestsList',
            platformapi__pb2.GetPendingRequestsListReq.SerializeToString,
            platformapi__pb2.GetPendingRequestsListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/VerifySignature',
            platformapi__pb2.VerifySignatureReq.SerializeToString,
            platformapi__pb2.VerifySignatureRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/CreateIdentity',
            platformapi__pb2.CreateIdentityReq.SerializeToString,
            platformapi__pb2.CreateIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/SignPayload',
            platformapi__pb2.SignPayloadReq.SerializeToString,
            platformapi__pb2.SignPayloadRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRejectedIdentitiesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetRejectedIdentitiesList',
            platformapi__pb2.GetRejectedIdentitiesListReq.SerializeToString,
            platformapi__pb2.GetRejectedIdentitiesListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidIdentitiesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetValidIdentitiesList',
            platformapi__pb2.GetValidIdentitiesListReq.SerializeToString,
            platformapi__pb2.GetValidIdentitiesListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidIdentityInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetValidIdentityInfo',
            platformapi__pb2.GetValidIdentityInfoReq.SerializeToString,
            platformapi__pb2.GetValidIdentityInfoRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordRejectedDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RecordRejectedDID',
            platformapi__pb2.RecordRejectedDIDReq.SerializeToString,
            platformapi__pb2.RecordRejectedDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRegistrationOfDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RequestRegistrationOfDevice',
            platformapi__pb2.RequestRegistrationOfDeviceReq.SerializeToString,
            platformapi__pb2.RequestRegistrationOfDeviceRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestIdentityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RequestIdentityStatus',
            platformapi__pb2.RequestIdentityStatusReq.SerializeToString,
            platformapi__pb2.RequestIdentityStatusRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocalStorageInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/LocalStorageInit',
            platformapi__pb2.LocalStorageInitReq.SerializeToString,
            platformapi__pb2.LocalStorageInitRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllDevicesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetAllDevicesList',
            platformapi__pb2.GetAllDevicesListReq.SerializeToString,
            platformapi__pb2.GetAllDevicesListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyDeviceDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/VerifyDeviceDID',
            platformapi__pb2.VerifyDeviceDIDReq.SerializeToString,
            platformapi__pb2.VerifyDeviceDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeDeviceDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RevokeDeviceDID',
            platformapi__pb2.RevokeDeviceDIDReq.SerializeToString,
            platformapi__pb2.RevokeDeviceDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDeviceDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RegisterDeviceDID',
            platformapi__pb2.RegisterDeviceDIDReq.SerializeToString,
            platformapi__pb2.RegisterDeviceDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlatformDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetPlatformDID',
            platformapi__pb2.GetPlatformDIDReq.SerializeToString,
            platformapi__pb2.GetPlatformDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevicePayloadsWithSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetDevicePayloadsWithSignature',
            platformapi__pb2.GetDevicePayloadsWithSignatureReq.SerializeToString,
            platformapi__pb2.GetDevicePayloadsWithSignatureRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostDeviceDataWithSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/PostDeviceDataWithSignature',
            platformapi__pb2.PostDeviceDataWithSignatureReq.SerializeToString,
            platformapi__pb2.PostDeviceDataWithSignatureRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCountriesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetCountriesList',
            platformapi__pb2.GetCountriesListReq.SerializeToString,
            platformapi__pb2.GetCountriesListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLicenseStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetLicenseStatus',
            platformapi__pb2.GetLicenseStatusReq.SerializeToString,
            platformapi__pb2.GetLicenseStatusRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignBytePayloadWithIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/SignBytePayloadWithIdentity',
            platformapi__pb2.SignBytePayloadWithIdentityReq.SerializeToString,
            platformapi__pb2.SignBytePayloadWithIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyBytePayloadWithIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/VerifyBytePayloadWithIdentity',
            platformapi__pb2.VerifyBytePayloadWithIdentityReq.SerializeToString,
            platformapi__pb2.VerifyBytePayloadWithIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/AddTags',
            platformapi__pb2.AddTagsReq.SerializeToString,
            platformapi__pb2.AddTagsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RemoveTags',
            platformapi__pb2.RemoveTagsReq.SerializeToString,
            platformapi__pb2.RemoveTagsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/GetTags',
            platformapi__pb2.GetTagsReq.SerializeToString,
            platformapi__pb2.GetTagsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignTagsToIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/AssignTagsToIdentity',
            platformapi__pb2.AssignTagsToIdentityReq.SerializeToString,
            platformapi__pb2.AssignTagsToIdentityRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIdentitiesUnderATag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/ListIdentitiesUnderATag',
            platformapi__pb2.ListIdentitiesUnderATagReq.SerializeToString,
            platformapi__pb2.ListIdentitiesUnderATagRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFiles(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/UploadFiles',
            platformapi__pb2.UploadFilesReq.SerializeToString,
            platformapi__pb2.UploadFilesRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/DownloadFiles',
            platformapi__pb2.DownloadFilesReq.SerializeToString,
            platformapi__pb2.DownloadFilesRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileStorePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/FileStorePath',
            platformapi__pb2.FileStorePathReq.SerializeToString,
            platformapi__pb2.FileStorePathRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordAppLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scuridplatformagentapi.v1.ScuridPlatformAgentAPI/RecordAppLogs',
            platformapiv2__pb2.RecordAppLogsReq.SerializeToString,
            platformapiv2__pb2.RecordAppLogsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
