# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rdbmsConfig.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rdbmsConfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dataStorageType_pb2 as dataStorageType__pb2
from metadata import metadata_pb2 as metadata_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rdbmsConfig.proto\x12\x0brdbmsConfig\x1a\x15\x64\x61taStorageType.proto\x1a\x17metadata/metadata.proto\"\xe6\x01\n\x13StoreRDBMSConfigReq\x12\x15\n\rdb_connection\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x62_name\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x10\n\x08\x64\x62_alias\x18\x05 \x01(\t\x12\x18\n\x10\x63reate_timestamp\x18\x06 \x01(\x03\x12\x18\n\x10update_timestamp\x18\x07 \x01(\x03\x12=\n\x0f\x64\x61taStorageType\x18\x08 \x01(\x0b\x32$.dataStorageType.v0.DataStorageTypes\"&\n\x13StoreRDBMSConfigRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x17\n\x15GetRDBMSConfigRequest\"F\n\x11GetRDBMSConfigRes\x12\x31\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32 .rdbmsConfig.StoreRDBMSConfigReq2\xe6\x01\n\x19RDBMSConfigurationService\x12\x62\n\x15GetRDBMSConfiguration\x12\".rdbmsConfig.GetRDBMSConfigRequest\x1a\x1e.rdbmsConfig.GetRDBMSConfigRes\"\x05\x8a\xb5\x18\x01\x01\x12\x65\n\x17StoreRDBMSConfiguration\x12 .rdbmsConfig.StoreRDBMSConfigReq\x1a .rdbmsConfig.StoreRDBMSConfigRes\"\x06\x8a\xb5\x18\x02\x02\x03\x42:Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/rdbmsConfig/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rdbmsConfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8bitbucket.org/scurid/scurid-apis/pkg/grpc/rdbmsConfig/v1'
  _globals['_RDBMSCONFIGURATIONSERVICE'].methods_by_name['GetRDBMSConfiguration']._loaded_options = None
  _globals['_RDBMSCONFIGURATIONSERVICE'].methods_by_name['GetRDBMSConfiguration']._serialized_options = b'\212\265\030\001\001'
  _globals['_RDBMSCONFIGURATIONSERVICE'].methods_by_name['StoreRDBMSConfiguration']._loaded_options = None
  _globals['_RDBMSCONFIGURATIONSERVICE'].methods_by_name['StoreRDBMSConfiguration']._serialized_options = b'\212\265\030\002\002\003'
  _globals['_STORERDBMSCONFIGREQ']._serialized_start=83
  _globals['_STORERDBMSCONFIGREQ']._serialized_end=313
  _globals['_STORERDBMSCONFIGRES']._serialized_start=315
  _globals['_STORERDBMSCONFIGRES']._serialized_end=353
  _globals['_GETRDBMSCONFIGREQUEST']._serialized_start=355
  _globals['_GETRDBMSCONFIGREQUEST']._serialized_end=378
  _globals['_GETRDBMSCONFIGRES']._serialized_start=380
  _globals['_GETRDBMSCONFIGRES']._serialized_end=450
  _globals['_RDBMSCONFIGURATIONSERVICE']._serialized_start=453
  _globals['_RDBMSCONFIGURATIONSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
