# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cdbstorage_pb2 as cdbstorage__pb2
import releasemanagement_pb2 as releasemanagement__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in releasemanagement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReleaseManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReleases = channel.unary_unary(
                '/releaseManagement.ReleaseManagementService/GetReleases',
                request_serializer=cdbstorage__pb2.GetReleasesReq.SerializeToString,
                response_deserializer=cdbstorage__pb2.GetReleasesRes.FromString,
                _registered_method=True)
        self.Download = channel.unary_stream(
                '/releaseManagement.ReleaseManagementService/Download',
                request_serializer=releasemanagement__pb2.DownloadReq.SerializeToString,
                response_deserializer=releasemanagement__pb2.DownloadRes.FromString,
                _registered_method=True)
        self.DownloadReleaseZip = channel.unary_stream(
                '/releaseManagement.ReleaseManagementService/DownloadReleaseZip',
                request_serializer=releasemanagement__pb2.DownloadReleaseZipReq.SerializeToString,
                response_deserializer=releasemanagement__pb2.DownloadReleaseZipRes.FromString,
                _registered_method=True)


class ReleaseManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReleases(self, request, context):
        """Get versions list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Called by clients to Download file(s)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadReleaseZip(self, request, context):
        """Request to download a zip file, containing all the files in the release from Edge Agent, Server & App etc.
        Request only need the version number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReleaseManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReleases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReleases,
                    request_deserializer=cdbstorage__pb2.GetReleasesReq.FromString,
                    response_serializer=cdbstorage__pb2.GetReleasesRes.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=releasemanagement__pb2.DownloadReq.FromString,
                    response_serializer=releasemanagement__pb2.DownloadRes.SerializeToString,
            ),
            'DownloadReleaseZip': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadReleaseZip,
                    request_deserializer=releasemanagement__pb2.DownloadReleaseZipReq.FromString,
                    response_serializer=releasemanagement__pb2.DownloadReleaseZipRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'releaseManagement.ReleaseManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('releaseManagement.ReleaseManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReleaseManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReleases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/releaseManagement.ReleaseManagementService/GetReleases',
            cdbstorage__pb2.GetReleasesReq.SerializeToString,
            cdbstorage__pb2.GetReleasesRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/releaseManagement.ReleaseManagementService/Download',
            releasemanagement__pb2.DownloadReq.SerializeToString,
            releasemanagement__pb2.DownloadRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadReleaseZip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/releaseManagement.ReleaseManagementService/DownloadReleaseZip',
            releasemanagement__pb2.DownloadReleaseZipReq.SerializeToString,
            releasemanagement__pb2.DownloadReleaseZipRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
