# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: releasemanagement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'releasemanagement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import release_pb2 as release__pb2
import cdbstorage_pb2 as cdbstorage__pb2
from metadata import metadata_pb2 as metadata_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17releasemanagement.proto\x12\x11releaseManagement\x1a\rrelease.proto\x1a\x10\x63\x64\x62storage.proto\x1a\x17metadata/metadata.proto\",\n\x0b\x44ownloadReq\x12\x1d\n\x05\x61sset\x18\x01 \x03(\x0b\x32\x0e.release.Asset\"(\n\x15\x44ownloadReleaseZipReq\x12\x0f\n\x07version\x18\x01 \x01(\t\"8\n\x0b\x44ownloadRes\x12)\n\x07version\x18\x01 \x01(\x0b\x32\x18.release.DownloadVersion\"B\n\x15\x44ownloadReleaseZipRes\x12)\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x1b.release.CompleteReleaseZip2\xb6\x02\n\x18ReleaseManagementService\x12R\n\x0bGetReleases\x12\x1d.cdbstorage.v1.GetReleasesReq\x1a\x1d.cdbstorage.v1.GetReleasesRes\"\x05\x8a\xb5\x18\x01\x01\x12S\n\x08\x44ownload\x12\x1e.releaseManagement.DownloadReq\x1a\x1e.releaseManagement.DownloadRes\"\x05\x8a\xb5\x18\x01\x01\x30\x01\x12q\n\x12\x44ownloadReleaseZip\x12(.releaseManagement.DownloadReleaseZipReq\x1a(.releaseManagement.DownloadReleaseZipRes\"\x05\x8a\xb5\x18\x01\x01\x30\x01\x42@Z>bitbucket.org/scurid/scurid-apis/pkg/grpc/releaseManagement/v0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'releasemanagement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>bitbucket.org/scurid/scurid-apis/pkg/grpc/releaseManagement/v0'
  _globals['_RELEASEMANAGEMENTSERVICE'].methods_by_name['GetReleases']._loaded_options = None
  _globals['_RELEASEMANAGEMENTSERVICE'].methods_by_name['GetReleases']._serialized_options = b'\212\265\030\001\001'
  _globals['_RELEASEMANAGEMENTSERVICE'].methods_by_name['Download']._loaded_options = None
  _globals['_RELEASEMANAGEMENTSERVICE'].methods_by_name['Download']._serialized_options = b'\212\265\030\001\001'
  _globals['_RELEASEMANAGEMENTSERVICE'].methods_by_name['DownloadReleaseZip']._loaded_options = None
  _globals['_RELEASEMANAGEMENTSERVICE'].methods_by_name['DownloadReleaseZip']._serialized_options = b'\212\265\030\001\001'
  _globals['_DOWNLOADREQ']._serialized_start=104
  _globals['_DOWNLOADREQ']._serialized_end=148
  _globals['_DOWNLOADRELEASEZIPREQ']._serialized_start=150
  _globals['_DOWNLOADRELEASEZIPREQ']._serialized_end=190
  _globals['_DOWNLOADRES']._serialized_start=192
  _globals['_DOWNLOADRES']._serialized_end=248
  _globals['_DOWNLOADRELEASEZIPRES']._serialized_start=250
  _globals['_DOWNLOADRELEASEZIPRES']._serialized_end=316
  _globals['_RELEASEMANAGEMENTSERVICE']._serialized_start=319
  _globals['_RELEASEMANAGEMENTSERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
