# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ssh_pb2 as ssh__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ssh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SSHTunnelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/SSHTunnel/Start',
                request_serializer=ssh__pb2.StartReq.SerializeToString,
                response_deserializer=ssh__pb2.StartRes.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/SSHTunnel/Stop',
                request_serializer=ssh__pb2.StopReq.SerializeToString,
                response_deserializer=ssh__pb2.StopRes.FromString,
                _registered_method=True)
        self.StatusStream = channel.unary_stream(
                '/SSHTunnel/StatusStream',
                request_serializer=ssh__pb2.StatusReq.SerializeToString,
                response_deserializer=ssh__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.SessionInfo = channel.unary_unary(
                '/SSHTunnel/SessionInfo',
                request_serializer=ssh__pb2.SessionInfoReq.SerializeToString,
                response_deserializer=ssh__pb2.SessionInfoRes.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/SSHTunnel/ListSessions',
                request_serializer=ssh__pb2.ListSessionsReq.SerializeToString,
                response_deserializer=ssh__pb2.ListSessionsRes.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/SSHTunnel/DeleteSession',
                request_serializer=ssh__pb2.DeleteSessionReq.SerializeToString,
                response_deserializer=ssh__pb2.DeleteSessionRes.FromString,
                _registered_method=True)


class SSHTunnelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatusStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SSHTunnelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=ssh__pb2.StartReq.FromString,
                    response_serializer=ssh__pb2.StartRes.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=ssh__pb2.StopReq.FromString,
                    response_serializer=ssh__pb2.StopRes.SerializeToString,
            ),
            'StatusStream': grpc.unary_stream_rpc_method_handler(
                    servicer.StatusStream,
                    request_deserializer=ssh__pb2.StatusReq.FromString,
                    response_serializer=ssh__pb2.StatusUpdate.SerializeToString,
            ),
            'SessionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionInfo,
                    request_deserializer=ssh__pb2.SessionInfoReq.FromString,
                    response_serializer=ssh__pb2.SessionInfoRes.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=ssh__pb2.ListSessionsReq.FromString,
                    response_serializer=ssh__pb2.ListSessionsRes.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=ssh__pb2.DeleteSessionReq.FromString,
                    response_serializer=ssh__pb2.DeleteSessionRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SSHTunnel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SSHTunnel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SSHTunnel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SSHTunnel/Start',
            ssh__pb2.StartReq.SerializeToString,
            ssh__pb2.StartRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SSHTunnel/Stop',
            ssh__pb2.StopReq.SerializeToString,
            ssh__pb2.StopRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatusStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SSHTunnel/StatusStream',
            ssh__pb2.StatusReq.SerializeToString,
            ssh__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SSHTunnel/SessionInfo',
            ssh__pb2.SessionInfoReq.SerializeToString,
            ssh__pb2.SessionInfoRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SSHTunnel/ListSessions',
            ssh__pb2.ListSessionsReq.SerializeToString,
            ssh__pb2.ListSessionsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SSHTunnel/DeleteSession',
            ssh__pb2.DeleteSessionReq.SerializeToString,
            ssh__pb2.DeleteSessionRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
