# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ssiapi_pb2 as ssiapi__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ssiapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SSIServiceAPIStub(object):
    """SSIServiceAPI provides set of services that will be exposed as APIs for -
    Platforms clients looking to interact with SSIService

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDeviceDID = channel.unary_unary(
                '/ssiapi.v1.SSIServiceAPI/RegisterDeviceDID',
                request_serializer=ssiapi__pb2.RegisterDeviceDIDReq.SerializeToString,
                response_deserializer=ssiapi__pb2.RegisterDeviceDIDRes.FromString,
                _registered_method=True)
        self.RegisterPlatformDID = channel.unary_unary(
                '/ssiapi.v1.SSIServiceAPI/RegisterPlatformDID',
                request_serializer=ssiapi__pb2.RegisterPlatformDIDReq.SerializeToString,
                response_deserializer=ssiapi__pb2.RegisterPlatformDIDRes.FromString,
                _registered_method=True)
        self.RevokeDeviceDID = channel.unary_unary(
                '/ssiapi.v1.SSIServiceAPI/RevokeDeviceDID',
                request_serializer=ssiapi__pb2.RevokeDeviceDIDReq.SerializeToString,
                response_deserializer=ssiapi__pb2.RevokeDeviceDIDRes.FromString,
                _registered_method=True)
        self.ResolveDID = channel.unary_unary(
                '/ssiapi.v1.SSIServiceAPI/ResolveDID',
                request_serializer=ssiapi__pb2.ResolveDIDReq.SerializeToString,
                response_deserializer=ssiapi__pb2.ResolveDIDRes.FromString,
                _registered_method=True)
        self.VerifyDeviceDID = channel.unary_unary(
                '/ssiapi.v1.SSIServiceAPI/VerifyDeviceDID',
                request_serializer=ssiapi__pb2.VerifyDeviceDIDReq.SerializeToString,
                response_deserializer=ssiapi__pb2.VerifyDeviceDIDRes.FromString,
                _registered_method=True)
        self.GetPlatformInfo = channel.unary_unary(
                '/ssiapi.v1.SSIServiceAPI/GetPlatformInfo',
                request_serializer=ssiapi__pb2.GetPlatformInfoReq.SerializeToString,
                response_deserializer=ssiapi__pb2.GetPlatformInfoRes.FromString,
                _registered_method=True)


class SSIServiceAPIServicer(object):
    """SSIServiceAPI provides set of services that will be exposed as APIs for -
    Platforms clients looking to interact with SSIService

    """

    def RegisterDeviceDID(self, request, context):
        """RegisterDeviceDID registers device DID in the blockchain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPlatformDID(self, request, context):
        """RegisterDeviceDID registers platform account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeDeviceDID(self, request, context):
        """RevokeDeviceDID marks did as revoked in the blockchain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveDID(self, request, context):
        """ResolveDID fetches device identity as DID document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyDeviceDID(self, request, context):
        """VerifyDID verifies device identity in terms of revocation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatformInfo(self, request, context):
        """GetPlatformInfoReq returns DID document and other platform information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SSIServiceAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDeviceDID': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDeviceDID,
                    request_deserializer=ssiapi__pb2.RegisterDeviceDIDReq.FromString,
                    response_serializer=ssiapi__pb2.RegisterDeviceDIDRes.SerializeToString,
            ),
            'RegisterPlatformDID': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlatformDID,
                    request_deserializer=ssiapi__pb2.RegisterPlatformDIDReq.FromString,
                    response_serializer=ssiapi__pb2.RegisterPlatformDIDRes.SerializeToString,
            ),
            'RevokeDeviceDID': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeDeviceDID,
                    request_deserializer=ssiapi__pb2.RevokeDeviceDIDReq.FromString,
                    response_serializer=ssiapi__pb2.RevokeDeviceDIDRes.SerializeToString,
            ),
            'ResolveDID': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveDID,
                    request_deserializer=ssiapi__pb2.ResolveDIDReq.FromString,
                    response_serializer=ssiapi__pb2.ResolveDIDRes.SerializeToString,
            ),
            'VerifyDeviceDID': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDeviceDID,
                    request_deserializer=ssiapi__pb2.VerifyDeviceDIDReq.FromString,
                    response_serializer=ssiapi__pb2.VerifyDeviceDIDRes.SerializeToString,
            ),
            'GetPlatformInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatformInfo,
                    request_deserializer=ssiapi__pb2.GetPlatformInfoReq.FromString,
                    response_serializer=ssiapi__pb2.GetPlatformInfoRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssiapi.v1.SSIServiceAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ssiapi.v1.SSIServiceAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SSIServiceAPI(object):
    """SSIServiceAPI provides set of services that will be exposed as APIs for -
    Platforms clients looking to interact with SSIService

    """

    @staticmethod
    def RegisterDeviceDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.SSIServiceAPI/RegisterDeviceDID',
            ssiapi__pb2.RegisterDeviceDIDReq.SerializeToString,
            ssiapi__pb2.RegisterDeviceDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPlatformDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.SSIServiceAPI/RegisterPlatformDID',
            ssiapi__pb2.RegisterPlatformDIDReq.SerializeToString,
            ssiapi__pb2.RegisterPlatformDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeDeviceDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.SSIServiceAPI/RevokeDeviceDID',
            ssiapi__pb2.RevokeDeviceDIDReq.SerializeToString,
            ssiapi__pb2.RevokeDeviceDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.SSIServiceAPI/ResolveDID',
            ssiapi__pb2.ResolveDIDReq.SerializeToString,
            ssiapi__pb2.ResolveDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyDeviceDID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.SSIServiceAPI/VerifyDeviceDID',
            ssiapi__pb2.VerifyDeviceDIDReq.SerializeToString,
            ssiapi__pb2.VerifyDeviceDIDRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlatformInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.SSIServiceAPI/GetPlatformInfo',
            ssiapi__pb2.GetPlatformInfoReq.SerializeToString,
            ssiapi__pb2.GetPlatformInfoRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ScuridGenericsStub(object):
    """This provides generic external APIs needed to perform tasks NOT PART of a DLT
    Offers storage, data distribution, data needed by the platform agent
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloScurid = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/HelloScurid',
                request_serializer=ssiapi__pb2.HelloScuridReq.SerializeToString,
                response_deserializer=ssiapi__pb2.HelloScuridRes.FromString,
                _registered_method=True)
        self.GetCountriesList = channel.unary_stream(
                '/ssiapi.v1.ScuridGenerics/GetCountriesList',
                request_serializer=ssiapi__pb2.GetCountriesListReq.SerializeToString,
                response_deserializer=ssiapi__pb2.GetCountriesListRes.FromString,
                _registered_method=True)
        self.RecordLicenseForUser = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/RecordLicenseForUser',
                request_serializer=ssiapi__pb2.RecordLicenseForUserReq.SerializeToString,
                response_deserializer=ssiapi__pb2.RecordLicenseForUserRes.FromString,
                _registered_method=True)
        self.LicenseStatusCheck = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/LicenseStatusCheck',
                request_serializer=ssiapi__pb2.LicenseStatusCheckReq.SerializeToString,
                response_deserializer=ssiapi__pb2.LicenseStatusCheckRes.FromString,
                _registered_method=True)
        self.GetReleases = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/GetReleases',
                request_serializer=ssiapi__pb2.GetReleasesReq.SerializeToString,
                response_deserializer=ssiapi__pb2.GetReleasesRes.FromString,
                _registered_method=True)
        self.Download = channel.unary_stream(
                '/ssiapi.v1.ScuridGenerics/Download',
                request_serializer=ssiapi__pb2.DownloadReq.SerializeToString,
                response_deserializer=ssiapi__pb2.DownloadRes.FromString,
                _registered_method=True)
        self.DownloadReleaseZip = channel.unary_stream(
                '/ssiapi.v1.ScuridGenerics/DownloadReleaseZip',
                request_serializer=ssiapi__pb2.DownloadReleaseZipReq.SerializeToString,
                response_deserializer=ssiapi__pb2.DownloadReleaseZipRes.FromString,
                _registered_method=True)
        self.RegisterUser = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/RegisterUser',
                request_serializer=ssiapi__pb2.RegisterUserReq.SerializeToString,
                response_deserializer=ssiapi__pb2.RegisterUserRes.FromString,
                _registered_method=True)
        self.SignUpUser = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/SignUpUser',
                request_serializer=ssiapi__pb2.InsertNewUserReq.SerializeToString,
                response_deserializer=ssiapi__pb2.InsertNewUserRes.FromString,
                _registered_method=True)
        self.LoginUser = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/LoginUser',
                request_serializer=ssiapi__pb2.LoginUserReq.SerializeToString,
                response_deserializer=ssiapi__pb2.LoginUserRes.FromString,
                _registered_method=True)
        self.AddPlan = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/AddPlan',
                request_serializer=ssiapi__pb2.AddPlanReq.SerializeToString,
                response_deserializer=ssiapi__pb2.AddPlanRes.FromString,
                _registered_method=True)
        self.GetPlan = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/GetPlan',
                request_serializer=ssiapi__pb2.GetPlanReq.SerializeToString,
                response_deserializer=ssiapi__pb2.GetPlanRes.FromString,
                _registered_method=True)
        self.GetPlatformUserInfo = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/GetPlatformUserInfo',
                request_serializer=ssiapi__pb2.VerificationReq.SerializeToString,
                response_deserializer=ssiapi__pb2.VerificationRes.FromString,
                _registered_method=True)
        self.ResetPassword = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/ResetPassword',
                request_serializer=ssiapi__pb2.ResetPasswordReq.SerializeToString,
                response_deserializer=ssiapi__pb2.ResetPasswordRes.FromString,
                _registered_method=True)
        self.UpdateUserPassword = channel.unary_unary(
                '/ssiapi.v1.ScuridGenerics/UpdateUserPassword',
                request_serializer=ssiapi__pb2.UpdateUserPasswordReq.SerializeToString,
                response_deserializer=ssiapi__pb2.UpdateUserPasswordRes.FromString,
                _registered_method=True)


class ScuridGenericsServicer(object):
    """This provides generic external APIs needed to perform tasks NOT PART of a DLT
    Offers storage, data distribution, data needed by the platform agent
    """

    def HelloScurid(self, request, context):
        """Scurid Test service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCountriesList(self, request, context):
        """get list of all countries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordLicenseForUser(self, request, context):
        """saves license related data for a users registering or the firt time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LicenseStatusCheck(self, request, context):
        """Validates if the license is still active
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReleases(self, request, context):
        """get list of releases
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Download the release
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadReleaseZip(self, request, context):
        """Request to download a zip file, containing all the files in the release from Edge Agent, Server & App etc.
        Request only need the version number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """Request new user registration
        this can be called from anywhere where simple user registration is needed
        e.g. from Scurid Getting Started page
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignUpUser(self, request, context):
        """SignUp new Users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """Request to Login to the Scurid portal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPlan(self, request, context):
        """Request to add new plans
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlan(self, request, context):
        """Request to get plan info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatformUserInfo(self, request, context):
        """Request to get verification status of the user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Resets the password of a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserPassword(self, request, context):
        """UpdateUserPassword updates the user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScuridGenericsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloScurid': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloScurid,
                    request_deserializer=ssiapi__pb2.HelloScuridReq.FromString,
                    response_serializer=ssiapi__pb2.HelloScuridRes.SerializeToString,
            ),
            'GetCountriesList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCountriesList,
                    request_deserializer=ssiapi__pb2.GetCountriesListReq.FromString,
                    response_serializer=ssiapi__pb2.GetCountriesListRes.SerializeToString,
            ),
            'RecordLicenseForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordLicenseForUser,
                    request_deserializer=ssiapi__pb2.RecordLicenseForUserReq.FromString,
                    response_serializer=ssiapi__pb2.RecordLicenseForUserRes.SerializeToString,
            ),
            'LicenseStatusCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.LicenseStatusCheck,
                    request_deserializer=ssiapi__pb2.LicenseStatusCheckReq.FromString,
                    response_serializer=ssiapi__pb2.LicenseStatusCheckRes.SerializeToString,
            ),
            'GetReleases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReleases,
                    request_deserializer=ssiapi__pb2.GetReleasesReq.FromString,
                    response_serializer=ssiapi__pb2.GetReleasesRes.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=ssiapi__pb2.DownloadReq.FromString,
                    response_serializer=ssiapi__pb2.DownloadRes.SerializeToString,
            ),
            'DownloadReleaseZip': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadReleaseZip,
                    request_deserializer=ssiapi__pb2.DownloadReleaseZipReq.FromString,
                    response_serializer=ssiapi__pb2.DownloadReleaseZipRes.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=ssiapi__pb2.RegisterUserReq.FromString,
                    response_serializer=ssiapi__pb2.RegisterUserRes.SerializeToString,
            ),
            'SignUpUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUpUser,
                    request_deserializer=ssiapi__pb2.InsertNewUserReq.FromString,
                    response_serializer=ssiapi__pb2.InsertNewUserRes.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=ssiapi__pb2.LoginUserReq.FromString,
                    response_serializer=ssiapi__pb2.LoginUserRes.SerializeToString,
            ),
            'AddPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPlan,
                    request_deserializer=ssiapi__pb2.AddPlanReq.FromString,
                    response_serializer=ssiapi__pb2.AddPlanRes.SerializeToString,
            ),
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=ssiapi__pb2.GetPlanReq.FromString,
                    response_serializer=ssiapi__pb2.GetPlanRes.SerializeToString,
            ),
            'GetPlatformUserInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatformUserInfo,
                    request_deserializer=ssiapi__pb2.VerificationReq.FromString,
                    response_serializer=ssiapi__pb2.VerificationRes.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=ssiapi__pb2.ResetPasswordReq.FromString,
                    response_serializer=ssiapi__pb2.ResetPasswordRes.SerializeToString,
            ),
            'UpdateUserPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserPassword,
                    request_deserializer=ssiapi__pb2.UpdateUserPasswordReq.FromString,
                    response_serializer=ssiapi__pb2.UpdateUserPasswordRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssiapi.v1.ScuridGenerics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ssiapi.v1.ScuridGenerics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScuridGenerics(object):
    """This provides generic external APIs needed to perform tasks NOT PART of a DLT
    Offers storage, data distribution, data needed by the platform agent
    """

    @staticmethod
    def HelloScurid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/HelloScurid',
            ssiapi__pb2.HelloScuridReq.SerializeToString,
            ssiapi__pb2.HelloScuridRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCountriesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/GetCountriesList',
            ssiapi__pb2.GetCountriesListReq.SerializeToString,
            ssiapi__pb2.GetCountriesListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordLicenseForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/RecordLicenseForUser',
            ssiapi__pb2.RecordLicenseForUserReq.SerializeToString,
            ssiapi__pb2.RecordLicenseForUserRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LicenseStatusCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/LicenseStatusCheck',
            ssiapi__pb2.LicenseStatusCheckReq.SerializeToString,
            ssiapi__pb2.LicenseStatusCheckRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReleases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/GetReleases',
            ssiapi__pb2.GetReleasesReq.SerializeToString,
            ssiapi__pb2.GetReleasesRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/Download',
            ssiapi__pb2.DownloadReq.SerializeToString,
            ssiapi__pb2.DownloadRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadReleaseZip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/DownloadReleaseZip',
            ssiapi__pb2.DownloadReleaseZipReq.SerializeToString,
            ssiapi__pb2.DownloadReleaseZipRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/RegisterUser',
            ssiapi__pb2.RegisterUserReq.SerializeToString,
            ssiapi__pb2.RegisterUserRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignUpUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/SignUpUser',
            ssiapi__pb2.InsertNewUserReq.SerializeToString,
            ssiapi__pb2.InsertNewUserRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/LoginUser',
            ssiapi__pb2.LoginUserReq.SerializeToString,
            ssiapi__pb2.LoginUserRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/AddPlan',
            ssiapi__pb2.AddPlanReq.SerializeToString,
            ssiapi__pb2.AddPlanRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/GetPlan',
            ssiapi__pb2.GetPlanReq.SerializeToString,
            ssiapi__pb2.GetPlanRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlatformUserInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/GetPlatformUserInfo',
            ssiapi__pb2.VerificationReq.SerializeToString,
            ssiapi__pb2.VerificationRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/ResetPassword',
            ssiapi__pb2.ResetPasswordReq.SerializeToString,
            ssiapi__pb2.ResetPasswordRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ScuridGenerics/UpdateUserPassword',
            ssiapi__pb2.UpdateUserPasswordReq.SerializeToString,
            ssiapi__pb2.UpdateUserPasswordRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
