# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storageSchemaMetadata.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'storageSchemaMetadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import compiled_protos.metadata_pb2 as metadata_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bstorageSchemaMetadata.proto\x12\x15storageSchemaMetadata\x1a\x17metadata/metadata.proto\"g\n\x1aStoreSchemaMetadataRequest\x12I\n\x14schemaMetadataStruct\x18\x01 \x01(\x0b\x32+.storageSchemaMetadata.SchemaMetadataStruct\".\n\x1bStoreSchemaMetadataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1a\n\x18GetSchemaMetadataRequest\"V\n\x19GetSchemaMetadataResponse\x12\x39\n\x04rows\x18\x01 \x03(\x0b\x32+.storageSchemaMetadata.SchemaMetadataStruct\"k\n\x14SchemaMetadataStruct\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\x1f\n\x17schemaMetadataStructure\x18\x02 \x01(\t\x12\x11\n\tcreatedOn\x18\x03 \x01(\x03\x12\x10\n\x08isGlobal\x18\x04 \x01(\x08\x32\xb6\x02\n\x1cStorageSchemaMetadataService\x12\x8c\x01\n\x1cStoreSchemaMetadataStructure\x12\x31.storageSchemaMetadata.StoreSchemaMetadataRequest\x1a\x32.storageSchemaMetadata.StoreSchemaMetadataResponse\"\x05\x8a\xb5\x18\x01\x02\x12\x86\x01\n\x1aGetSchemaMetadataStructure\x12/.storageSchemaMetadata.GetSchemaMetadataRequest\x1a\x30.storageSchemaMetadata.GetSchemaMetadataResponse\"\x05\x8a\xb5\x18\x01\x01\x42\x44ZBbitbucket.org/scurid/scurid-apis/pkg/grpc/storageSchemaMetadata/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storageSchemaMetadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBbitbucket.org/scurid/scurid-apis/pkg/grpc/storageSchemaMetadata/v1'
  _globals['_STORAGESCHEMAMETADATASERVICE'].methods_by_name['StoreSchemaMetadataStructure']._loaded_options = None
  _globals['_STORAGESCHEMAMETADATASERVICE'].methods_by_name['StoreSchemaMetadataStructure']._serialized_options = b'\212\265\030\001\002'
  _globals['_STORAGESCHEMAMETADATASERVICE'].methods_by_name['GetSchemaMetadataStructure']._loaded_options = None
  _globals['_STORAGESCHEMAMETADATASERVICE'].methods_by_name['GetSchemaMetadataStructure']._serialized_options = b'\212\265\030\001\001'
  _globals['_STORESCHEMAMETADATAREQUEST']._serialized_start=79
  _globals['_STORESCHEMAMETADATAREQUEST']._serialized_end=182
  _globals['_STORESCHEMAMETADATARESPONSE']._serialized_start=184
  _globals['_STORESCHEMAMETADATARESPONSE']._serialized_end=230
  _globals['_GETSCHEMAMETADATAREQUEST']._serialized_start=232
  _globals['_GETSCHEMAMETADATAREQUEST']._serialized_end=258
  _globals['_GETSCHEMAMETADATARESPONSE']._serialized_start=260
  _globals['_GETSCHEMAMETADATARESPONSE']._serialized_end=346
  _globals['_SCHEMAMETADATASTRUCT']._serialized_start=348
  _globals['_SCHEMAMETADATASTRUCT']._serialized_end=455
  _globals['_STORAGESCHEMAMETADATASERVICE']._serialized_start=458
  _globals['_STORAGESCHEMAMETADATASERVICE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
