# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storageSchemaMetadata_pb2 as storageSchemaMetadata__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in storageSchemaMetadata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageSchemaMetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreSchemaMetadataStructure = channel.unary_unary(
                '/storageSchemaMetadata.StorageSchemaMetadataService/StoreSchemaMetadataStructure',
                request_serializer=storageSchemaMetadata__pb2.StoreSchemaMetadataRequest.SerializeToString,
                response_deserializer=storageSchemaMetadata__pb2.StoreSchemaMetadataResponse.FromString,
                _registered_method=True)
        self.GetSchemaMetadataStructure = channel.unary_unary(
                '/storageSchemaMetadata.StorageSchemaMetadataService/GetSchemaMetadataStructure',
                request_serializer=storageSchemaMetadata__pb2.GetSchemaMetadataRequest.SerializeToString,
                response_deserializer=storageSchemaMetadata__pb2.GetSchemaMetadataResponse.FromString,
                _registered_method=True)


class StorageSchemaMetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreSchemaMetadataStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchemaMetadataStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageSchemaMetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreSchemaMetadataStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreSchemaMetadataStructure,
                    request_deserializer=storageSchemaMetadata__pb2.StoreSchemaMetadataRequest.FromString,
                    response_serializer=storageSchemaMetadata__pb2.StoreSchemaMetadataResponse.SerializeToString,
            ),
            'GetSchemaMetadataStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemaMetadataStructure,
                    request_deserializer=storageSchemaMetadata__pb2.GetSchemaMetadataRequest.FromString,
                    response_serializer=storageSchemaMetadata__pb2.GetSchemaMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storageSchemaMetadata.StorageSchemaMetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storageSchemaMetadata.StorageSchemaMetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageSchemaMetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreSchemaMetadataStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storageSchemaMetadata.StorageSchemaMetadataService/StoreSchemaMetadataStructure',
            storageSchemaMetadata__pb2.StoreSchemaMetadataRequest.SerializeToString,
            storageSchemaMetadata__pb2.StoreSchemaMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchemaMetadataStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storageSchemaMetadata.StorageSchemaMetadataService/GetSchemaMetadataStructure',
            storageSchemaMetadata__pb2.GetSchemaMetadataRequest.SerializeToString,
            storageSchemaMetadata__pb2.GetSchemaMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
