# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: useragreementandpricing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'useragreementandpricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1duseragreementandpricing.proto\x12\x1auseragreementandpricing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n\x16ServiceAgreementStruct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x64ocument\x18\x04 \x01(\t\x12-\n\tcreatedAt\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0blastUpdated\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x61\x63tive\x18\x07 \x01(\x08\"\xfe\x01\n\x1aUserServiceAgreementStruct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tuserEmail\x18\x02 \x01(\t\x12\x1c\n\x14service_agreement_id\x18\x03 \x01(\t\x12-\n\tagreed_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0clast_updated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x42\n\x06status\x18\x06 \x01(\x0e\x32\x32.useragreementandpricing.v1.ServiceAgreementStatus*M\n\x16ServiceAgreementStatus\x12\x0b\n\x07unknown\x10\x00\x12\n\n\x06\x61\x63tive\x10\x01\x12\r\n\tsuspended\x10\x02\x12\x0b\n\x07\x65xpired\x10\x03\x42\x46ZDbitbucket.org/scurid/scurid-apis/pkg/grpc/useragreementandpricing/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'useragreementandpricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDbitbucket.org/scurid/scurid-apis/pkg/grpc/useragreementandpricing/v1'
  _globals['_SERVICEAGREEMENTSTATUS']._serialized_start=558
  _globals['_SERVICEAGREEMENTSTATUS']._serialized_end=635
  _globals['_SERVICEAGREEMENTSTRUCT']._serialized_start=95
  _globals['_SERVICEAGREEMENTSTRUCT']._serialized_end=299
  _globals['_USERSERVICEAGREEMENTSTRUCT']._serialized_start=302
  _globals['_USERSERVICEAGREEMENTSTRUCT']._serialized_end=556
# @@protoc_insertion_point(module_scope)
