# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import userLicensing_pb2 as userLicensing__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in userLicensing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PricingStub(object):
    """This wraps the Stripe APIs for the SSI service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddCustomer = channel.unary_unary(
                '/ssiapi.v1.Pricing/AddCustomer',
                request_serializer=userLicensing__pb2.AddCustomerReq.SerializeToString,
                response_deserializer=userLicensing__pb2.AddCustomerRes.FromString,
                _registered_method=True)
        self.GetPriceTable = channel.unary_unary(
                '/ssiapi.v1.Pricing/GetPriceTable',
                request_serializer=userLicensing__pb2.GetPriceTableReq.SerializeToString,
                response_deserializer=userLicensing__pb2.GetPriceTableRes.FromString,
                _registered_method=True)


class PricingServicer(object):
    """This wraps the Stripe APIs for the SSI service
    """

    def AddCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomer,
                    request_deserializer=userLicensing__pb2.AddCustomerReq.FromString,
                    response_serializer=userLicensing__pb2.AddCustomerRes.SerializeToString,
            ),
            'GetPriceTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceTable,
                    request_deserializer=userLicensing__pb2.GetPriceTableReq.FromString,
                    response_serializer=userLicensing__pb2.GetPriceTableRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssiapi.v1.Pricing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ssiapi.v1.Pricing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pricing(object):
    """This wraps the Stripe APIs for the SSI service
    """

    @staticmethod
    def AddCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.Pricing/AddCustomer',
            userLicensing__pb2.AddCustomerReq.SerializeToString,
            userLicensing__pb2.AddCustomerRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPriceTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.Pricing/GetPriceTable',
            userLicensing__pb2.GetPriceTableReq.SerializeToString,
            userLicensing__pb2.GetPriceTableRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceAgreementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServiceAgreement = channel.unary_unary(
                '/ssiapi.v1.ServiceAgreement/GetServiceAgreement',
                request_serializer=userLicensing__pb2.GetServiceAgreementReq.SerializeToString,
                response_deserializer=userLicensing__pb2.GetServiceAgreementRes.FromString,
                _registered_method=True)
        self.GetUserAgreement = channel.unary_unary(
                '/ssiapi.v1.ServiceAgreement/GetUserAgreement',
                request_serializer=userLicensing__pb2.GetUserAgreementReq.SerializeToString,
                response_deserializer=userLicensing__pb2.GetUserAgreementRes.FromString,
                _registered_method=True)
        self.StoreUserToServiceAgreement = channel.unary_unary(
                '/ssiapi.v1.ServiceAgreement/StoreUserToServiceAgreement',
                request_serializer=userLicensing__pb2.UserToServiceAgreementReq.SerializeToString,
                response_deserializer=userLicensing__pb2.UserToServiceAgreementRes.FromString,
                _registered_method=True)


class ServiceAgreementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServiceAgreement(self, request, context):
        """to be called by clients to get the service agreement
        returns only active service agreements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAgreement(self, request, context):
        """to be called by clients to get the service agreement acceptance for a given email address
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreUserToServiceAgreement(self, request, context):
        """to be called by clients to store the acceptance of the service agreement for a given email address
        this same API can also be called when there is a need to update the service agreement acceptance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceAgreementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServiceAgreement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceAgreement,
                    request_deserializer=userLicensing__pb2.GetServiceAgreementReq.FromString,
                    response_serializer=userLicensing__pb2.GetServiceAgreementRes.SerializeToString,
            ),
            'GetUserAgreement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAgreement,
                    request_deserializer=userLicensing__pb2.GetUserAgreementReq.FromString,
                    response_serializer=userLicensing__pb2.GetUserAgreementRes.SerializeToString,
            ),
            'StoreUserToServiceAgreement': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreUserToServiceAgreement,
                    request_deserializer=userLicensing__pb2.UserToServiceAgreementReq.FromString,
                    response_serializer=userLicensing__pb2.UserToServiceAgreementRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssiapi.v1.ServiceAgreement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ssiapi.v1.ServiceAgreement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceAgreement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServiceAgreement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ServiceAgreement/GetServiceAgreement',
            userLicensing__pb2.GetServiceAgreementReq.SerializeToString,
            userLicensing__pb2.GetServiceAgreementRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserAgreement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ServiceAgreement/GetUserAgreement',
            userLicensing__pb2.GetUserAgreementReq.SerializeToString,
            userLicensing__pb2.GetUserAgreementRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreUserToServiceAgreement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ssiapi.v1.ServiceAgreement/StoreUserToServiceAgreement',
            userLicensing__pb2.UserToServiceAgreementReq.SerializeToString,
            userLicensing__pb2.UserToServiceAgreementRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
