# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import weavechain_pb2 as weavechain__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in weavechain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeavechainStub(object):
    """For integration with Weavechain Inc.
    services defined here are for INTERNAL USE ONLY!
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CustomerProfile = channel.unary_unary(
                '/integration.v1.Weavechain/CustomerProfile',
                request_serializer=weavechain__pb2.CustomerProfileReq.SerializeToString,
                response_deserializer=weavechain__pb2.CustomerProfileRes.FromString,
                _registered_method=True)
        self.GetDeviceData = channel.unary_stream(
                '/integration.v1.Weavechain/GetDeviceData',
                request_serializer=weavechain__pb2.DeviceDataReq.SerializeToString,
                response_deserializer=weavechain__pb2.DeviceDataRes.FromString,
                _registered_method=True)
        self.GetCustomersEnabledForMonetization = channel.unary_stream(
                '/integration.v1.Weavechain/GetCustomersEnabledForMonetization',
                request_serializer=weavechain__pb2.GetCustomersEnabledForMonetizationReq.SerializeToString,
                response_deserializer=weavechain__pb2.GetCustomersEnabledForMonetizationRes.FromString,
                _registered_method=True)


class WeavechainServicer(object):
    """For integration with Weavechain Inc.
    services defined here are for INTERNAL USE ONLY!
    """

    def CustomerProfile(self, request, context):
        """CustomerProfile containing metadata, e.g. preferences for monetization, pricing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceData(self, request, context):
        """GetDeviceData for monetization
        Server streaming API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomersEnabledForMonetization(self, request, context):
        """GetCustomersEnabledForMonetization provides list of customers currently enabled for monetization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeavechainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CustomerProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomerProfile,
                    request_deserializer=weavechain__pb2.CustomerProfileReq.FromString,
                    response_serializer=weavechain__pb2.CustomerProfileRes.SerializeToString,
            ),
            'GetDeviceData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDeviceData,
                    request_deserializer=weavechain__pb2.DeviceDataReq.FromString,
                    response_serializer=weavechain__pb2.DeviceDataRes.SerializeToString,
            ),
            'GetCustomersEnabledForMonetization': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCustomersEnabledForMonetization,
                    request_deserializer=weavechain__pb2.GetCustomersEnabledForMonetizationReq.FromString,
                    response_serializer=weavechain__pb2.GetCustomersEnabledForMonetizationRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'integration.v1.Weavechain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('integration.v1.Weavechain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Weavechain(object):
    """For integration with Weavechain Inc.
    services defined here are for INTERNAL USE ONLY!
    """

    @staticmethod
    def CustomerProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integration.v1.Weavechain/CustomerProfile',
            weavechain__pb2.CustomerProfileReq.SerializeToString,
            weavechain__pb2.CustomerProfileRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/integration.v1.Weavechain/GetDeviceData',
            weavechain__pb2.DeviceDataReq.SerializeToString,
            weavechain__pb2.DeviceDataRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomersEnabledForMonetization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/integration.v1.Weavechain/GetCustomersEnabledForMonetization',
            weavechain__pb2.GetCustomersEnabledForMonetizationReq.SerializeToString,
            weavechain__pb2.GetCustomersEnabledForMonetizationRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
